### PR TITLE
Change the tag naming convention

### LINKED ISSUE #6673: Change tag format to use vx.x.x
## Description
Currently we have script that automate the tag generation and they use the following format:
`v{Wazuh_mayor}.{Wazuh_minor}.{Wazuh_path}-{Opensearch_mayor}.{Opensearch_minor}.{Opensearch_patch}`

We must change this to user only Wazuh version as the name of the tag:
`v{Wazuh_mayor}.{Wazuh_minor}.{Wazuh_path}`

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Change tag handling script to use only Wazuh version as the name of a tag. E.g. v4.9.0
- [x] Analyze how this impacts documentation

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull requests changes the tag naming convention to match with the rest of Wazuh components using the format:
`v{major}.{minor}.{patch}`

Changes
- Adapt tag.js script
- Adapt RELEASING.md file

### Issues Resolved
#6673

### Evidence
<details>

```
node scripts/release/tag.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --tag-suffix -test1
[WARN][tag]: version is not defined. Using from the current package manifest ./plugins/main/package.json: 4.9.0
[WARN][tag]: revision is not defined. Using from the current package manifest ./plugins/main/package.json]: 00
[WARN][tag]: platform version is not defined. Using from the current package manifest ./plugins/main/package.json: 2.13.0
[INFO][tag]: Version: 4.9.0
[INFO][tag]: Revision: 00
[INFO][tag]: Platform version: 2.13.0
[INFO][tag]: Tag suffix: -test1
[INFO][tag]: Tag name: v4.9.0-test1
[WARN][tag]: Ensure the base branch is created in the remote and it has updated the files that are not modified by the bump process. See RELEASING.md.
[WARN][tag]: This script will prune the local branches and tags, bump the plugins, commit and push the tags to the remote repository, deleting any unpushed changes. It is required you have configurated the repository to sign the commit and tag creation.
Do you want to continue? [y/N] y
[INFO][tag]: Run command: git checkout 4.9.0
Cambiado a rama '4.9.0'
[INFO][tag]: Switched to branch: 4.9.0
[INFO][tag]: Run command: git fetch --prune --prune-tags --force
Desde https://github.com/wazuh/wazuh-kibana-app
 - [eliminado]           (nada)     -> v4.9.0--test1
[INFO][tag]: Pruned local branches and tags
[INFO][tag]: Generating tag: v4.9.0-test1...
[INFO][bump]: Plugin directories from ./plugins: main, wazuh-check-updates, wazuh-core
[INFO][bump][main]: Version: 4.9.0
[INFO][bump][main]: Revision: 00
[INFO][bump][main]: Platform version: 2.13.0
[INFO][bump][main]: Package manifest: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main/package.json
[INFO][bump][main]: Plugin manifest: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main/opensearch_dashboards.json
[INFO][bump][main]: This will update the manifest files: package and platform plugin.
[INFO][bump][main]: Updated /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main/package.json
[INFO][bump][main]: Updated /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main/opensearch_dashboards.json
[INFO][bump][main]: Calling to specific bump script
[INFO][bump][main][specific]: Run command: cd /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main && yarn generate:api-data --spec https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml
{
  displayConfiguration: true,
  displayExamples: false,
  displayHelp: false,
  format: 'plugin',
  output: 'file',
  spec: 'https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml',
  outputDirectory: '/home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main/common/api-info'
}
yarn run v1.21.1
$ node scripts/generate-api-data.js --spec https://raw.githubusercontent.com/wazuh/wazuh/$(node -e "console.log(require('./package.json').version)")/api/api/spec/spec.yaml --output file --output-directory common/api-info --display-configuration --spec https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml
File was created! Path: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main/common/api-info/security-actions.json
File was created! Path: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/main/common/api-info/endpoints.json
Done in 2.36s.

[INFO][bump][wazuh-check-updates]: Version: 4.9.0
[INFO][bump][wazuh-check-updates]: Revision: 00
[INFO][bump][wazuh-check-updates]: Platform version: 2.13.0
[INFO][bump][wazuh-check-updates]: Package manifest: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-check-updates/package.json
[INFO][bump][wazuh-check-updates]: Plugin manifest: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-check-updates/opensearch_dashboards.json
[INFO][bump][wazuh-check-updates]: This will update the manifest files: package and platform plugin.
[INFO][bump][wazuh-check-updates]: Updated /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-check-updates/package.json
[INFO][bump][wazuh-check-updates]: Updated /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-check-updates/opensearch_dashboards.json
[INFO][bump][wazuh-core]: Version: 4.9.0
[INFO][bump][wazuh-core]: Revision: 00
[INFO][bump][wazuh-core]: Platform version: 2.13.0
[INFO][bump][wazuh-core]: Package manifest: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-core/package.json
[INFO][bump][wazuh-core]: Plugin manifest: /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-core/opensearch_dashboards.json
[INFO][bump][wazuh-core]: This will update the manifest files: package and platform plugin.
[INFO][bump][wazuh-core]: Updated /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-core/package.json
[INFO][bump][wazuh-core]: Updated /home/toni/wazuh/src/wazuh-kibana-app/.worktrees/osd/plugins/wazuh-core/opensearch_dashboards.json
Review the changes done with the bump. y (continue), d (list changes: git diff), f (list modified files: git diff --name-only), N/n (cancel) f
[INFO][tag]: Run command: git diff --name-only

Review the changes done with the bump. y (continue), d (list changes: git diff), f (list modified files: git diff --name-only), N/n (cancel) y
[INFO][tag]: Run command: git diff --exit-code --no-patch;echo -n $?
[INFO][tag]: There are not changes to commit.
[INFO][tag]: Run command: git tag -s -a v4.9.0-test1 -m "Wazuh plugins for Wazuh dashboard v4.9.0-test1"
[INFO][tag]: Created tag: v4.9.0-test1
```
</details>

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## Other

| Test | Result |
| --- |  --- |
| Ensure the tag name generated by the tag script uses the format v{wazuh_version}{suffix} | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the tag name generated by the tag script uses the format v{wazuh_version}{suffix}</summary>

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
## Test

| Test | Result |
| --- |  --- |
| Ensure the tag name generated by the tag script uses the format v{wazuh_version}{suffix} | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the tag name generated by the tag script uses the format v{wazuh_version}{suffix}</summary>


#### Command:

```
node scripts/release/tag.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json
```

#### Output:

```
[WARN][tag]: version is not defined. Using from the current package manifest ./plugins/main/package.json: 4.9.0
[WARN][tag]: revision is not defined. Using from the current package manifest ./plugins/main/package.json]: 00
[WARN][tag]: platform version is not defined. Using from the current package manifest ./plugins/main/package.json: 2.13.0
[INFO][tag]: Version: 4.9.0
[INFO][tag]: Revision: 00
[INFO][tag]: Platform version: 2.13.0
[INFO][tag]: Tag name: v4.9.0
[WARN][tag]: Ensure the base branch is created in the remote and it has updated the files that are not modified by the bump process. See RELEASING.md.
[WARN][tag]: This script will prune the local branches and tags, bump the plugins, commit and push the tags to the remote repository, deleting any unpushed changes. It is required you have configurated the repository to sign the commit and tag creation.
Do you want to continue? [y/N] y
[INFO][tag]: Run command: git checkout 4.9.0
Switched to branch '4.9.0'
[INFO][tag]: Switched to branch: 4.9.0
[INFO][tag]: Run command: git fetch --prune --prune-tags --force
[INFO][tag]: Pruned local branches and tags
[INFO][tag]: Generating tag: v4.9.0...
[INFO][bump]: Plugin directories from ./plugins: main, wazuh-check-updates, wazuh-core
[INFO][bump][main]: Version: 4.9.0
[INFO][bump][main]: Revision: 00
[INFO][bump][main]: Platform version: 2.13.0
[INFO][bump][main]: Package manifest: /home/usuario/wazuh-dashboard-plugins/plugins/main/package.json
[INFO][bump][main]: Plugin manifest: /home/usuario/wazuh-dashboard-plugins/plugins/main/opensearch_dashboards.json
[INFO][bump][main]: This will update the manifest files: package and platform plugin.
[INFO][bump][main]: Updated /home/usuario/wazuh-dashboard-plugins/plugins/main/package.json
[INFO][bump][main]: Updated /home/usuario/wazuh-dashboard-plugins/plugins/main/opensearch_dashboards.json
[INFO][bump][main]: Calling to specific bump script
[INFO][bump][main][specific]: Run command: cd /home/usuario/wazuh-dashboard-plugins/plugins/main && yarn generate:api-data --spec https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml
{
  displayConfiguration: true,
  displayExamples: false,
  displayHelp: false,
  format: 'plugin',
  output: 'file',
  spec: 'https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml',
  outputDirectory: '/home/usuario/wazuh-dashboard-plugins/plugins/main/common/api-info'
}
yarn run v1.22.19
$ node scripts/generate-api-data.js --spec https://raw.githubusercontent.com/wazuh/wazuh/$(node -e "console.log(require('./package.json').version)")/api/api/spec/spec.yaml --output file --output-directory common/api-info --display-configuration --spec https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml
File was created! Path: /home/usuario/wazuh-dashboard-plugins/plugins/main/common/api-info/security-actions.json
File was created! Path: /home/usuario/wazuh-dashboard-plugins/plugins/main/common/api-info/endpoints.json
Done in 1.62s.

[INFO][bump][wazuh-check-updates]: Version: 4.9.0
[INFO][bump][wazuh-check-updates]: Revision: 00
[INFO][bump][wazuh-check-updates]: Platform version: 2.13.0
[INFO][bump][wazuh-check-updates]: Package manifest: /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-check-updates/package.json
[INFO][bump][wazuh-check-updates]: Plugin manifest: /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-check-updates/opensearch_dashboards.json
[INFO][bump][wazuh-check-updates]: This will update the manifest files: package and platform plugin.
[INFO][bump][wazuh-check-updates]: Updated /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-check-updates/package.json
[INFO][bump][wazuh-check-updates]: Updated /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-check-updates/opensearch_dashboards.json
[INFO][bump][wazuh-core]: Version: 4.9.0
[INFO][bump][wazuh-core]: Revision: 00
[INFO][bump][wazuh-core]: Platform version: 2.13.0
[INFO][bump][wazuh-core]: Package manifest: /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-core/package.json
[INFO][bump][wazuh-core]: Plugin manifest: /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-core/opensearch_dashboards.json
[INFO][bump][wazuh-core]: This will update the manifest files: package and platform plugin.
[INFO][bump][wazuh-core]: Updated /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-core/package.json
[INFO][bump][wazuh-core]: Updated /home/usuario/wazuh-dashboard-plugins/plugins/wazuh-core/opensearch_dashboards.json
Review the changes done with the bump. y (continue), d (list changes: git diff), f (list modified files: git diff --name-only), N/n (cancel) y
[INFO][tag]: Run command: git diff --exit-code --no-patch;echo -n $?
[INFO][tag]: There are changes to commit.
[INFO][tag]: Run command: git diff --name-only
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/package.json

[INFO][tag]: Run command: git commit -S -am "Bump v4.9.0"
[INFO][tag]: Commited
[INFO][tag]: Run command: git tag -s -a v4.9.0 -m "Wazuh plugins for Wazuh dashboard v4.9.0"

```

#### Command:

```
$ git tag -l | grep 4.9.0
```
#### Output:

```
v4.9.0
```




</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Comment by JuanGarriuz** [comment]
Into the discover plugin, I see a warning about the OpenSearch version. it must be investigated.

image

**Comment by asteriscos** [comment]
| Test | Result |
| --- |  --- |
| Ensure the tag name generated by the tag script uses the format v{wazuh_version}{suffix} | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the tag name generated by the tag script uses the format v{wazuh_version}{suffix}</summary>

</details>

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
