### PR TITLE
Fix maximize in embeddable vulnerability panel

### PR DESCRIPTION
**Pull request by jbiset**
## Description
This pull request fix maximize in embeddable dashboards panels.
`dshLayout-isMaximizedPanel` is a specific class that adds OSD to the ResponsiveGrid component when a panel is expanded.
Since this fix is needed in more than one embedded dashboard, it was decided to apply the CSS at the highest possible level but within the context of Wazuh.
 
## Issues Resolved
- #6322 

## Evidence
[Evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/ac1d3ce0-e223-462c-9456-a30d3396b92d)

### Steps to test:
- Go to vulnerability module.
- Go to panel actions of a panel ("···" button)
- Select maximize panel.
- The panel occupy the entire space of the module.
- Check correct operation with the menu bar

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by yenienserrano — COMMENTED** [review]
CR: ✅  Should it be in the changelog?

**Review by yenienserrano — APPROVED** [review]
LGTM

**Comment by JuanGarriuz** [comment]
<details><summary>Tests ✅</summary>

image

image

image

image

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Pull request merged**
