### PR TITLE
Implement embeddable dashboard on HIPAA

### LINKED ISSUE #6507: [Remove discover] Implement embeddable dashboard on HIPAA module
## Description

We have to implement the embeddable dashboard on HIPAA -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Implement the embeddable dashboard on HIPAA -> `Dashboard` tab
- [x] Implement the embeddable dashboard on HIPAA -> `Controls` tab
- [x] Implement the embeddable dashboard on HIPAA -> `Events` tab

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request replaces the `Dashboard` tab on HIPAA application.

### Issues Resolved
#6507

### Evidence
image
image
image

#### Go to HIPAA > Dashboard

- Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.
- The visualizations have to be updated according to the filters applied in the searchbar.
- The visualizations have to be updated when a search is performed in the searchbar.
- If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
- If there is SampleData, the corresponding SampleData message must appear.
- If an agent is pinned, the views must be updated and changed to the agent view, if applicable.
- Check filter behavior with respect to hide alerts, allow agents and filter order.

#### Go to HIPAA > Controls

- Check the requirements filters on the on the left side filters the requirements on the right side
- Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.
- In the details flyout click on the show on dashboard and events links, they should display this tabs with a filter related to the selected requirement
- The link on the flyout table should redirect to Endpoint Summary and Rules respectively

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# Changes
- Update the development branch.
- Fix hide filter control on the Dashboard tab.

**Comment by yenienserrano** [comment]
## Test

### Go to HIPAA > Dashboard:

- [ ] Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.
- [ ] The visualizations have to be updated according to the filters applied in the searchbar.
- [ ] The visualizations have to be updated when a search is performed in the searchbar.
- [ ] If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
- [ ] If there is SampleData, the corresponding SampleData message must appear.
- [ ] If an agent is pinned, the views must be updated and changed to the agent view, if applicable.
- [ ] Check filter behavior with respect to hide alerts, allow agents and filter order.

### Go to HIPAA > Controls
- [ ] Check the requirements filters on the on the left side filters the requirements on the right side
- [ ] Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. - [ ] The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.
- [ ] In the details flyout click on the show on dashboard and events links, they should display this tabs with a filter related to the selected requirement
- [ ] The link on the flyout table should redirect to Endpoint Summary and Rules respectively

**Review by yenienserrano — APPROVED** [review]
CR: ✅ 
Test: ✔️

**Comment by asteriscos** [comment]
## Test

### Go to HIPAA > Dashboard:

#### :green_circle: Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.

<details><summary>Details</summary>

image


</details> 

#### :green_circle: The visualizations have to be updated according to the filters applied in the searchbar.

<details><summary>Details</summary>

image

</details> 

#### :green_circle: The visualizations have to be updated when a search is performed in the searchbar.

<details><summary>Details</summary>

image


</details> 

#### :green_circle:  If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.

<details><summary>Details</summary>

image


</details> 

#### :green_circle:  If there is SampleData, the corresponding SampleData message must appear.

<details><summary>Details</summary>

image


</details> 

#### :green_circle:  If an agent is pinned, the views must be updated and changed to the agent view, if applicable.

<details><summary>Details</summary>

image


</details> 

#### :green_circle: Check filter behavior with respect to hide alerts, allow agents and filter order.

<details><summary>Details</summary>

image


</details> 


### Go to HIPAA > Controls
#### Check the requirements filters on the on the left side filters the requirements on the right side.

<details><summary>Details</summary>


</details> 

#### Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. 

<details><summary>Details</summary>


</details> 

#### The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.

<details><summary>Details</summary>


</details> 

#### In the details flyout click on the show on dashboard and events links, they should display this tabs with a filter related to the selected requirement

<details><summary>Details</summary>


</details> 

#### The link on the flyout table should redirect to Endpoint Summary and Rules respectively

<details><summary>Details</summary>


</details>

**Comment by Desvelao** [comment]
@asteriscos I was reviewing the finding about the `The rule tab has no information about the rule`, and there is not a rule with the specified ID `479`. I think the alert could be generated through the sample data. Could you check it?

**Comment by asteriscos** [comment]
Yes, you are right. I re-tested it and it seems it was because of the sample data. Aparently it created alerts with rule IDs non-existent.

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
