### PR TITLE
Add visualization of vulnerabilities evaluation status count

### LINKED ISSUE #6957: User interface toggle for vulnerability evaluation status
## Description

There are some vulnerabilities that have not been evaluated yet, therefore some fields are missing.
This issue aims to implement a toggle in the user interface to display the dispute/evaluation status using the `wazuh.vulnerability.under_evaluation` filter.

Vulnerabilities still under evaluation:
image

## Tasks
- [ ] Create a filter control that allows the user to filter `wazuh.vulnerability.under_evaluation` by `true` or `false`
  - This could be done by:
    - developing a new action button like the `Explore agent` selector 
image

    - or perhaps a new type of control in the "implicit filters" section of the search bar.
image

- [x] Adapt Wazuh dashboard sample data to consider this case, so it can be easily tested.

### Vulnerabilities dashboard
image

### Vulnerabilities inventory
image

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request adds a visualization to the `Vulnerabilities Detection > Dashboard` related to evaluation status count.

#### Side changes
- Fix a rendering problem in the WzDataGrid component that was not using the field formatter
 
### Issues Resolved
#6957

### Evidenc

https://github.com/user-attachments/assets/e94c34c2-a61d-412b-b660-aa6a5e7a625e

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Use the under_evaluation quick filter and check if the data react (toggle the filter) | :black_circle: | :black_circle: | :black_circle: |
| Apply the under_evaluation quick filter and switch between Dashboard and Inventory tab, the filter must be preserved | :black_circle: | :black_circle: | :black_circle: |
| Apply the under_evaluation quick filter and switch between `Dashboard` and `Inventory` tab, refresh the browser and check if the filter persists | :black_circle: | :black_circle: | :black_circle: |
| Add the under_evaluation filter and check if the quick filter state changes | :black_circle: | :black_circle: | :black_circle: |

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by guidomodarelli** [comment]
:green_circle: Test
:green_circle: CR

image

**Review by guidomodarelli — APPROVED** [review]

**Comment by Desvelao** [comment]
> CR: 🟢 Test: Perhaps color can be added as we have had issues with color when they were black. #6856
> 
> image

I was reviewing the topic with the label colors. There are no more options available in the visualization creator and taking into account the colors for the labes on the indicators of the `Vulnerabilities Detection > Dashboard`, I think to differenciate the indicators, we could keep the dark grey (light mode) displayed in the screenshots.

In the case we want to change the color, this could be done using styles, but the visualization definition does not offer more options:
image

**Review by Machi3mfl — APPROVED** [review]
CR: ✅ 
Test: ✅ 

Screenshot 2024-09-05 at 12 43 24

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!!

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With vulnerabilities states data, go to Vulnerabilities Detection > Dashboard, and it should display a visulization releated to evaluation status | :green_circle: | :black_circle: | :black_circle: |
| With vulnerabilities states data, go to Vulnerabilities Detection > Inventory, and add the `wazuh.vulnerability.under_evaluation` field to the table and this should display the values in the table cells | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: With vulnerabilities states data, go to Vulnerabilities Detection > Dashboard, and it should display a visulization releated to evaluation status</summary>

Chrome - :green_circle:


image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: With vulnerabilities states data, go to Vulnerabilities Detection > Inventory, and add the `wazuh.vulnerability.under_evaluation` field to the table and this should display the values in the table cells</summary>

Chrome - :green_circle:


image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by chantal-kelm — DISMISSED** [review]
LGTM!!!

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With vulnerabilities states data, go to Vulnerabilities Detection > Dashboard, and it should display a visulization releated to evaluation status | :green_circle: | :black_circle: | :black_circle: |
| With vulnerabilities states data, go to Vulnerabilities Detection > Inventory, and add the `wazuh.vulnerability.under_evaluation` field to the table and this should display the values in the table cells | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: With vulnerabilities states data, go to Vulnerabilities Detection > Dashboard, and it should display a visulization releated to evaluation status</summary>

Chrome - :green_circle:


Captura de pantalla 2024-09-18 a la(s) 12 16 28 p  m


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: With vulnerabilities states data, go to Vulnerabilities Detection > Inventory, and add the `wazuh.vulnerability.under_evaluation` field to the table and this should display the values in the table cells</summary>

Chrome - :green_circle:


Captura de pantalla 2024-09-18 a la(s) 12 19 24 p  m


Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by asteriscos — APPROVED** [review]
CR: :green_circle: 
Test: :green_circle: 


https://github.com/user-attachments/assets/e541067e-8e6f-46c7-8904-5d331943a4ae

**Review by chantal-kelm — DISMISSED** [review]
CR: ✅ 
TEST: ✅ 


Uploading Grabación de pantalla 2024-09-26 a la(s) 4.45.47 p. m..mov…

**Review by chantal-kelm — DISMISSED** [review]

**Comment by guidomodarelli** [comment]
Test :red_circle: 
image

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
