### PR TITLE
Replace discover PCI DSS, GDPR, HIPAA, TSC and NIST 800-53 modules 

### PR DESCRIPTION
**Pull request by JuanGarriuz**
### Description
This PR, replaces the events tab on the PCI DSS, GDPR, HIPAA, TSC and NIST 800-53 modules
 
### Issues Resolved

[PCI DSS module](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6295)
[GDPR module](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6296)
[HIPAA module](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6298)
[TSC module](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6300)
[NIST 800-53 module](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6299)

### PCI DSS
image

### GDPR
image

### HIPAA
image

### NIST 800-53
image

### TSC

image

# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |

<details> <summary>Apply filters using search bar input</summary>

</details>

<details><summary>Apply filters using the search bar `add filter` feature</summary>

</details>

<details><summary>Apply filters using the date picker</summary>

</details>

<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>

</details>

<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>

</details>

## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |

<details><summary>Check histogram chart hits consistency </summary>

</details>

<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |

<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>

</details>

<details><summary>Check table pagination and rows per page</summary>

</details>

<details><summary>Check document detail flyout</summary>

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by yenienserrano** [comment]
PCI DSS

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |



<details> <summary>Apply filters using search bar input</summary>


</details>



<details><summary>Apply filters using the search bar `add filter` feature</summary>


</details>



<details><summary>Apply filters using the date picker</summary>


</details>



<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>


</details>



<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>


</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |



<details><summary>Check histogram chart hits consistency </summary>


</details>




<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>


</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |



<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>


</details>




<details><summary>Check table pagination and rows per page</summary>


</details>



<details><summary>Check document detail flyout</summary>


</details>

**Comment by yenienserrano** [comment]
GDPR

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :green_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :green_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :green_circle: | :black_circle: | :black_circle: |



<details> <summary>Apply filters using search bar input</summary>

image

</details>



<details><summary>Apply filters using the search bar `add filter` feature</summary>

image

</details>



<details><summary>Apply filters using the date picker</summary>

image

</details>



<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>

image

</details>



<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>

image

</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | 🟢  | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check histogram chart hits consistency </summary>

image

</details>


<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>

image

image

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :green_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :green_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>

image

image

image

image

image

</details>




<details><summary>Check table pagination and rows per page</summary>

image

</details>



<details><summary>Check document detail flyout</summary>

image

</details>

**Comment by yenienserrano** [comment]
HIPAA

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :green_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :green_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :green_circle: | :black_circle: | :black_circle: |



<details> <summary>Apply filters using search bar input</summary>

image

</details>



<details><summary>Apply filters using the search bar `add filter` feature</summary>

image

</details>



<details><summary>Apply filters using the date picker</summary>

image

</details>



<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>

image

</details>



<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>

image

</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | 🟢  | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check histogram chart hits consistency </summary>

image

</details>


<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>

image

image

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :green_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :green_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>

image

image

image

image

image

</details>




<details><summary>Check table pagination and rows per page</summary>

image

</details>



<details><summary>Check document detail flyout</summary>

image

</details>

**Comment by yenienserrano** [comment]
NIST 800-53

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :green_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :green_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :green_circle: | :black_circle: | :black_circle: |



<details> <summary>Apply filters using search bar input</summary>

image

</details>



<details><summary>Apply filters using the search bar `add filter` feature</summary>

image

</details>



<details><summary>Apply filters using the date picker</summary>

image

</details>



<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>

image

</details>



<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>

image

</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | 🟢  | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check histogram chart hits consistency </summary>

image

</details>


<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>

image
image

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :green_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :green_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>

image
image
image
image
image

</details>





<details><summary>Check table pagination and rows per page</summary>

image

</details>



<details><summary>Check document detail flyout</summary>

image

</details>

**Comment by yenienserrano** [comment]
TSC

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :green_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :green_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :green_circle: | :black_circle: | :black_circle: |



<details> <summary>Apply filters using search bar input</summary>

image

</details>



<details><summary>Apply filters using the search bar `add filter` feature</summary>

image

</details>



<details><summary>Apply filters using the date picker</summary>

image

</details>



<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>

image

</details>



<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>

image

</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | 🟢  | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check histogram chart hits consistency </summary>

image

</details>


<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>

image
image

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :green_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :green_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :green_circle: | :black_circle: | :black_circle: |



<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>

image
image
image
image
image

</details>





<details><summary>Check table pagination and rows per page</summary>

image

</details>



<details><summary>Check document detail flyout</summary>

image

</details>

**Review by yenienserrano — APPROVED** [review]
LGTM

**Comment by Machi3mfl** [comment]
# DGPR - Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |



<details> <summary>Apply filters using search bar input</summary>


</details>



<details><summary>Apply filters using the search bar `add filter` feature</summary>


</details>



<details><summary>Apply filters using the date picker</summary>


</details>



<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>


</details>



<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>


</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |



<details><summary>Check histogram chart hits consistency </summary>


</details>




<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>


</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |



<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>


</details>




<details><summary>Check table pagination and rows per page</summary>


</details>



<details><summary>Check document detail flyout</summary>


</details>

**Comment by Machi3mfl** [comment]
# NIST 800-53 - Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |



<details> <summary>Apply filters using search bar input</summary>


</details>



<details><summary>Apply filters using the search bar `add filter` feature</summary>


</details>



<details><summary>Apply filters using the date picker</summary>


</details>



<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>


</details>



<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>


</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |



<details><summary>Check histogram chart hits consistency </summary>


</details>




<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>


</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |



<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>


</details>




<details><summary>Check table pagination and rows per page</summary>


</details>



<details><summary>Check document detail flyout</summary>


</details>

**Review by Machi3mfl — DISMISSED** [review]

**Review by yenienserrano — APPROVED** [review]

**Review by Machi3mfl — APPROVED** [review]

**Review by yenienserrano — APPROVED** [review]

**Pull request merged**
