### PR TITLE
Add agent columns to vulnerabilities inventory table

### LINKED ISSUE #6350: Add agent name and id  in vulnerability inventory as a default field
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | alpha 2 | Chrome, Firefox, Safari, etc |

**Description**
We need to add agent name and the agent id as a default field in the inventory table for vulnerabilities. The first two fields in the table should be these ones.

We will want to add the cluster name, but we don't have a field name yet. 

**Steps to reproduce**
1. Navigate to 'Vulnerabilities -> Inventory
2. Review columns

**Screenshots**

image

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
This pull request adds `agent.name` and `agent.id` columns to the Vulnerabilities / Inventory table. It also fixes the use-docked-side-nav custom hook to evaluate the width of the viewport, which fixes the way the full-screen feature of the table is rendered in smaller windows.
 
### Issues Resolved
#6350 

### Evidence
image

### Test
- Go to Vulnerabilities / Inventory
- Use the full-screen feature of the Inventory table with and without the docked side navigation menu
- Check the table has the columns:

| agent.id | agent.name | package.name | package.version | vulnerability.severity | vulnerability.id | vulnerability.score.version | vulnerability.score.base |
| --- | --- | --- | --- | --- | --- | --- | --- |

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by yenienserrano — DISMISSED** [review]
CR: ✅ 
Test: ✅ 

image

**Comment by gdiazlo** [comment]
I believe we need to remove the `vulnerability.score.version` from the table as a default field. That way there will be less fields by default and it will be more readable in smaller windows.

**Comment by asteriscos** [comment]
> I believe we need to remove the `vulnerability.score.version` from the table as a default field. That way there will be less fields by default and it will be more readable in smaller windows.

I removed the column. :heavy_check_mark: 

image

**Review by lucianogorza — APPROVED** [review]
## CR 🟢 
## Test 🟢 
image

**Review by yenienserrano — DISMISSED** [review]

**Review by lucianogorza — APPROVED** [review]
## Test 🟢 
image

**Review by chantal-kelm — APPROVED** [review]
CR: ✅ 
TEST: ✅ 

image

**Pull request merged**
