### PR TITLE
Remove tools and dev tools AngularJS controllers

### LINKED ISSUE #6536: [Remove discover] Refactor angularJS blank-screen-controller.js
# Description

To deprecate angularJS in the plugins we need to refactor the blank-screen-controller.js into a react component.
The file is located in: _/main/public/controllers/misc/blank-screen-controller.js_

### LINKED ISSUE #6539: [Remove discover] Refactor AngularJS tools and dev tools controllers
# Description

To deprecate angularJS in the plugins we need to refactor the tools and dev tools controllers into a ReactJS component.
The files are located in:
- _/plugins/main/public/controllers/tools/tools.ts_
- _/plugins/main/public/controllers/dev-tools/dev-tools.ts_

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request removes the tools and dev tools AngularJS controllers.

Changes:
- Remove dev tools and tools controllers
- Replace the render using an AngularJS template by a ReactJS component
- Create ToolsRouter component to manage the routing of Dev Tools and
  Ruleset Test views
- Move logic and render of dev tools to a ReactJS component
- Remove unused definitions of controllers and variables in AngularJS
 
### Issues Resolved
#6539 

### Evidence
image
image

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to Server management > Dev Tools and the application should be visible | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, test the API endpoint suggestions are working as previously | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, run API requests, the response should be displayed in the reghit side | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the button to get more information about the current API endpoint in the editor of the left side | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the link to get information about the API referene that is located in the top right corner | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the button to export the output of API request to JSON. Verify the file content has the same content that was displayed in the output view when this was exported | :black_circle: | :black_circle: | :black_circle: |
| Go to Server management > Dev Tools and the breadcrumb should display the name of the application | :black_circle: | :black_circle: | :black_circle: |
| Go to Server management > Ruleset Test and the application should be visible | :black_circle: | :black_circle: | :black_circle: |
| Go to Server management > Ruleset Test and the breadcrumb should display the name of the application | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Go to Server management > Dev Tools and the application should be visible</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, test the API endpoint suggestions are working as previously</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, run API requests, the response should be displayed in the reghit side</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, click on the button to get more information about the current API endpoint in the editor of the left side</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, click on the link to get information about the API referene that is located in the top right corner</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, click on the button to export the output of API request to JSON. Verify the file content has the same content that was displayed in the output view when this was exported</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to Server management > Dev Tools and the breadcrumb should display the name of the application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to Server management > Ruleset Test and the application should be visible</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to Server management > Ruleset Test and the breadcrumb should display the name of the application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to Server management > Dev Tools and the application should be visible | 🟢  | :black_circle: | :black_circle: |
| In Server management > Dev Tools, test the API endpoint suggestions are working as previously | :green_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, run API requests, the response should be displayed in the reghit side | :green_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the button to get more information about the current API endpoint in the editor of the left side | :green_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the link to get information about the API referene that is located in the top right corner | :green_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the button to export the output of API request to JSON. Verify the file content has the same content that was displayed in the output view when this was exported | :green_circle: | :black_circle: | :black_circle: |
| Go to Server management > Dev Tools and the breadcrumb should display the name of the application | :green_circle: | :black_circle: | :black_circle: |
| Go to Server management > Ruleset Test and the application should be visible | :green_circle: | :black_circle: | :black_circle: |
| Go to Server management > Ruleset Test and the breadcrumb should display the name of the application | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Go to Server management > Dev Tools and the application should be visible</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: In Server management > Dev Tools, test the API endpoint suggestions are working as previously</summary>

Chrome - :green_circle:
image
image
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: In Server management > Dev Tools, run API requests, the response should be displayed in the reghit side</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: In Server management > Dev Tools, click on the button to get more information about the current API endpoint in the editor of the left side</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: In Server management > Dev Tools, click on the link to get information about the API reference that is located in the top right corner</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: In Server management > Dev Tools, click on the button to export the output of API request to JSON. Verify the file content has the same content that was displayed in the output view when this was exported</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Go to Server management > Dev Tools and the breadcrumb should display the name of the application</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Go to Server management > Ruleset Test and the application should be visible</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Go to Server management > Ruleset Test and the breadcrumb should display the name of the application</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Go to Server management > Ruleset Test and the breadcrumb should display the name of the application</summary>

Chrome - :green_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Comment by yenienserrano** [comment]
| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to Server management > Dev Tools and the application should be visible | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, test the API endpoint suggestions are working as previously | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, run API requests, the response should be displayed in the reghit side | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the button to get more information about the current API endpoint in the editor of the left side | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the link to get information about the API referene that is located in the top right corner | :black_circle: | :black_circle: | :black_circle: |
| In Server management > Dev Tools, click on the button to export the output of API request to JSON. Verify the file content has the same content that was displayed in the output view when this was exported | :black_circle: | :black_circle: | :black_circle: |
| Go to Server management > Dev Tools and the breadcrumb should display the name of the application | :black_circle: | :black_circle: | :black_circle: |
| Go to Server management > Ruleset Test and the application should be visible | :black_circle: | :black_circle: | :black_circle: |
| Go to Server management > Ruleset Test and the breadcrumb should display the name of the application | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Go to Server management > Dev Tools and the application should be visible</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, test the API endpoint suggestions are working as previously</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, run API requests, the response should be displayed in the reghit side</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, click on the button to get more information about the current API endpoint in the editor of the left side</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, click on the link to get information about the API referene that is located in the top right corner</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Server management > Dev Tools, click on the button to export the output of API request to JSON. Verify the file content has the same content that was displayed in the output view when this was exported</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to Server management > Dev Tools and the breadcrumb should display the name of the application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to Server management > Ruleset Test and the application should be visible</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to Server management > Ruleset Test and the breadcrumb should display the name of the application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by yenienserrano — APPROVED** [review]
CR: ✅ 
Test: ✅

**Pull request merged**
