### PR TITLE
Leave the date of last modification on a single line on the FIM > Inventory > Windows Registry

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description

In FIM > Inventory > Windows Registry table the last modification date was split and made the table bigger, add space and render in 1 line.  
 
### Issues Resolved

- #6874 

### Evidence

image

### Test

1. Navigate to 'FIM > inventory > windows registry'
2. View the date

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by chantal-kelm** [comment]
The date is shown on two lines:

image

**Review by Machi3mfl — APPROVED** [review]
CR: ✅ 
Test: ✅ 

Screenshot 2024-07-29 at 14 36 22

**Comment by Desvelao** [comment]
# Changes

- Enhance API responses on the mock server

**Review by chantal-kelm — APPROVED** [review]
image

**Review by Desvelao — APPROVED** [review]
LGTM!

**Pull request merged**
