### PR TITLE
[Vulnerabilities dashboards] Add global vulnerabilities dashboards

### LINKED ISSUE #5763: [Update dashboards] Global vulnerabilities dashboards
## Introduction

With the new vulnerability detector work (https://github.com/wazuh/wazuh/issues/14153), we can start implementing a global vulnerability dashboard which can manage all detected vulnerabilities across all endpoints.

We will implement this dashboard under Modules / Vulnerabilities: 

image

without selecting an agent, this page will show the default dashboard, which will be designed like the following mock:

image

We won't be using the embedded Discover to implement the inventory or the vulnerabilities table, instead, we will use a standard table component with an expand action, which will display a fly-out with the details about the vulnerability selected. This design will take advantage of the new vulnerabilities index schema to ensure all vulnerabilities contain a minimum set of information required by our users.

The single agent dashboard will use the global one with an agent filter applied.

## Development plan

In order to create the new vulnerabilities dashboard we need to define different tasks/steps:

- **Research stage**
  - [x] wazuh/wazuh-kibana-app#5800
  - [x] wazuh/wazuh-kibana-app#5839
  
- **Components and services**
  - [x] #5945
    - Known issue solved: https://github.com/wazuh/wazuh-kibana-app/issues/5969
  - [x] #5946
  
- **Demo stage**
  - [x] #5894
  - [x] #5895

- **Improve and fixes stage**
  - [x] #6064

  
> - Create visualization definitions using the OSD Visualize plugin (2.9.0) and the new vulnerabilities index pattern.
> - Use the dashboard plugin react component to render the vis definitions created in the previous step
> - Add a searchbar component to filter the events
> - Repeat the process for the dashboard and inventory tabs
  
- **Test and documentation stage**
  - [x] Add unit test, e2e testing, etc.
  - [x] Add documentation to reuse in other module dashboards

### We want to implement a new `dashboard` tab:

- [x] Vulnerabilities search bar
  - We must use the platform search bar component
  - We must search in the new vulnerability index
  - Each time we search, all the dashboard must update to reflect the results based on the search bar filter
- [x] ~~Cross search vulnerability with alerts~~
  - ~~Investigate how can we cross-search the vulnerability index with the general alerts index to search for additional information from within the vulnerability dashboard~~ (It's not possible cross-search the vulnerability index with the general alerts index)
- [x] Filter by vulnerable product
  - A user must be able to quickly select a product from a list and add it as a filter to the search bar
- [x] Filter by operating system version
  -  A user must be able to quickly select an OS version from a list and add it as a filter to the search bar
- [x] Easy filter by agent group
  -  A user must be able to quickly select an endpoint group from a list and add it as a filter to the search bar
- [x] ~~cves by severity~~ 
  - ~~A user must be able to quickly see the amount of CVEs by severity: critical, high, medium, low~~ (There is not enough information in the index to make a graph like this. Replaced with Accumulation of the most detected vulnerabilities)
- [x] open vs closed vulnerabilities over time
  - A user must be able to quickly see the tendency of open vs closes vulnerabilities. This information comes from the alerts index, instead of the vulnerabilities one, so this graph must have its own time filter
- [x] top 10s graphs
  - A user must be able to see 
    - the most detected vulnerabilities
    - the most vulnerable endpoints
    - ...
- [x] vulnerabilities table
   - sort by values like the vulnerability score
   - ~~actions:~~
     - ~~See details on a fly out ~~(It's not possible)
     - ~~Go to alerts index with a filter by that vulnerability~~ (It's not possible)
- [x] ~~evaluate the performance of the dashboard in scenarios with thousands of endpoints~~ (does not apply to this issue)
- [x] ~~Reporting~~ (this functionality will be implemented later)
  - ~~A user should be able to export the query results~~
  - ~~A user should be able to create a report out of the dashboard~~

We might need to implement new configuration options to support the new vulnerability detector under the current configuration module.

- [x] New vulnerability detector configuration options

### We want to implement a new `inventory` tab:

- [x] Add related native searchbar
- [x] New inventory table using native indexer table (as is possible)
- [x] Add filters and columns switcher 

## Dependencies

This work depends on the vulnerability index schema and a set of sample data to build the queries to generate and test the dashboard visualizations and queries.

## Related issues

We will add here issues from our backlog and projects related to this effort.

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description

This PR, adds the following features:

1. New global vulnerabilities dashboard
2. Replace the inventory panel

Closes #5763 

### Test

1. Generate random data for the vulnerabilities module (https://github.com/wazuh/wazuh-dashboard-plugins/issues/5763#issuecomment-1779564103)
2. Go to Modules -> Vulnerabilities and test following

| Test | Result |
| --- |  --- |
| Check that the dashboard tab looks like the reference in the comment (https://github.com/wazuh/wazuh-dashboard-plugins/pull/5896#issuecomment-1790919849). | :black_circle: |
| Check that the inventory tab looks like the reference in the comment (https://github.com/wazuh/wazuh-dashboard-plugins/pull/5896#issuecomment-1789606985). | :black_circle: |
| Use search bar input to filter any word and check if the dashboard shows the corresponding results. | :black_circle: |
| Select an option from one of the recommended filters and check that the corresponding filter is added and the dashboard changes according to the applied filter. | :black_circle: |
| Add a filter through interaction with a visualization and check that the dashboard updates. | :black_circle: |
| Add a filter on search bar and the dashboard changes according to the applied filter. | :black_circle: |
| Use search bar input to filter any word and check if the table shows the corresponding results. | :black_circle: |
| Use the input and type an incorrect word to check if the no results message is shown. | :black_circle: |
| Use the add filters button, select any filter and check if the table shows the corresponding results. | :black_circle: |
| Use the page and rows per page selector, and check if is working as expected. | :black_circle: |
| Use the data grid toolbar controls functionality (columns selector, density, sort fields, full screen). | :black_circle: |
| Use export formatted control (export table to CSV button). | :black_circle: |
| Use the header columns controls (column visibility, column sorting, column position). | :black_circle: |
| Click on the inspect document button and check the flyout functionality, the details must show the row clicked on the table. | :black_circle: |

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Machi3mfl** [comment]
# Inventory tab

Screenshot 2023-11-01 at 17 09 25

## Test cases

- Use search bar input to filter any word and check if the table shows the corresponding results

Screenshot 2023-11-01 at 16 58 17

- Use the input and type an incorrect word to check if the no results message is shown

Screenshot 2023-11-01 at 17 01 22

- Use the `add filters` button, select any filter and check if the table shows the corresponding results

Screenshot 2023-11-01 at 16 59 54

- Use the page and rows per page selector, and check if is working as expected

Screenshot 2023-11-01 at 17 03 11

Screenshot 2023-11-01 at 17 03 48

- Use the data grid toolbar controls functionality (columns selector, density, sort fields, full screen)

Screenshot 2023-11-01 at 17 06 17

- Use export formatted control (export table to CSV button)

Screenshot 2023-11-01 at 17 07 42

- Use the header columns controls (column visibility, column sorting, column position)

Screenshot 2023-11-01 at 17 08 14

- Click on the inspect document button and check the flyout functionality, the details must show the row clicked on the table.

Screenshot 2023-11-01 at 17 10 08

**Comment by lucianogorza** [comment]
| Test | Result |
| --- |  --- |
| Check that the dashboard tab looks like the reference in the comment. | :black_circle: |
| Check that the inventory tab looks like the reference in the comment. | :black_circle: |
| Use search bar input to filter any word and check if the dashboard shows the corresponding results. | :black_circle: |
| Select an option from one of the recommended filters and check that the corresponding filter is added and the dashboard changes according to the applied filter. | :black_circle: |
| Add a filter through interaction with a visualization and check that the dashboard updates. | :black_circle: |
| Add a filter on search bar and the dashboard changes according to the applied filter. | :black_circle: |
| Use search bar input to filter any word and check if the table shows the corresponding results. | :black_circle: |
| Use the input and type an incorrect word to check if the no results message is shown. | :black_circle: |
| Use the add filters button, select any filter and check if the table shows the corresponding results. | :black_circle: |
| Use the page and rows per page selector, and check if is working as expected. | :black_circle: |
| Use the data grid toolbar controls functionality (columns selector, density, sort fields, full screen). | :black_circle: |
| Use export formatted control (export table to CSV button). | :black_circle: |
| Use the header columns controls (column visibility, column sorting, column position). | :black_circle: |
| Click on the inspect document button and check the flyout functionality, the details must show the row clicked on the table. | :black_circle: |

**Comment by jbiset** [comment]
## Dashboard Tab

### Light mode

vulnerabilities_dashboard_1

vulnerabilities_dashboard_2


### Dark mode
vulnerabilities_dashboard_1_dark

vulnerabilities_dashboard_2_dark

**Review by lucianogorza — APPROVED** [review]

**Review by jbiset — APPROVED** [review]
## CR: :green_circle: 

## TEST

| Test | Result |
| --- |  --- |
| Check that the dashboard tab looks like the reference in the comment (https://github.com/wazuh/wazuh-dashboard-plugins/pull/5896#issuecomment-1790919849). | :green_circle: |
| Check that the inventory tab looks like the reference in the comment (https://github.com/wazuh/wazuh-dashboard-plugins/pull/5896#issuecomment-1789606985). | :green_circle: |
| Use search bar input to filter any word and check if the dashboard shows the corresponding results. | :green_circle: |
| Select an option from one of the recommended filters and check that the corresponding filter is added and the dashboard changes according to the applied filter. | :green_circle: |
| Add a filter through interaction with a visualization and check that the dashboard updates. | :yellow_circle: |
| Add a filter on search bar and the dashboard changes according to the applied filter. | :green_circle: |
| Use search bar input to filter any word and check if the table shows the corresponding results. | :green_circle: |
| Use the input and type an incorrect word to check if the no results message is shown. | :green_circle: |
| Use the add filters button, select any filter and check if the table shows the corresponding results. | :green_circle: |
| Use the page and rows per page selector, and check if is working as expected. | :yellow_circle: |
| Use the data grid toolbar controls functionality (columns selector, density, sort fields, full screen). | :yellow_circle: |
| Use export formatted control (export table to CSV button). | :yellow_circle: |
| Use the header columns controls (column visibility, column sorting, column position). | :green_circle: |
| Click on the inspect document button and check the flyout functionality, the details must show the row clicked on the table. | :green_circle: |


### DETAILS

<details>
<summary>
:green_circle:  Check that the dashboard tab looks like the reference in the comment (https://github.com/wazuh/wazuh-dashboard-plugins/pull/5896#issuecomment-1790919849).
</summary>

00_dashboard_tab_1

00_dashboard_tab_2


</details>

<details>
<summary>
:green_circle: Check that the inventory tab looks like the reference in the comment (https://github.com/wazuh/wazuh-dashboard-plugins/pull/5896#issuecomment-1789606985)
</summary>

01_inventory_tab

</details>

<details>
<summary>
:green_circle: Use search bar input to filter any word and check if the dashboard shows the corresponding results.
</summary>

02_dashboard_tab_search_word

</details>

<details>
<summary>
:green_circle: Select an option from one of the recommended filters and check that the corresponding filter is added and the dashboard changes according to the applied filter.
</summary>

03_dashboard_tab_recommended_filter

</details>

<details>
<summary>
:yellow_circle: Add a filter through interaction with a visualization and check that the dashboard updates
</summary>

04_dashboard_tab_visualization_interaction_1

04_dashboard_tab_visualization_interaction_2

04_dashboard_tab_visualization_interaction_3

</details>

<details>
<summary>
:green_circle: Add a filter on search bar and the dashboard changes according to the applied filter
</summary>

05_dashboard_tab_filter_searchbar_1

05_dashboard_tab_filter_searchbar_2


</details>

<details>
<summary>
:green_circle: Use search bar input to filter any word and check if the table shows the corresponding results
</summary>

07_inventory_tab_search_word

</details>

<details>
<summary>
:green_circle: Use the input and type an incorrect word to check if the no results message is shown
</summary>

08_inventory_tab_search_no_match

</details>

<details>
<summary>
:green_circle: Use the add filters button, select any filter and check if the table shows the corresponding results.
</summary>

09_inventory_tab_filter_searchbar_1

09_inventory_tab_filter_searchbar_2

</details>

<details>
<summary>
:yellow_circle: Use the page and rows per page selector, and check if is working as expected
</summary>

10_inventory_tab_pagination_1

10_inventory_tab_pagination_2

10_inventory_tab_pagination_3

10_inventory_tab_pagination_4_A

10_inventory_tab_pagination_4_B

**NOTE**: _Bad request when from + size is not less than or equal to 10000_
**Related documentation**: https://opensearch.org/docs/latest/im-plugin/index-settings/#dynamic-index-settings

</details>


<details>
<summary>
:yellow_circle: Use the data grid toolbar controls functionality (columns selector, density, sort fields, full screen) and Use the header columns controls (column visibility, column sorting, column position).
</summary>

#### :green_circle:  Columns selector

11_inventory_tab_column_selector_1

11_inventory_tab_column_selector_2


#### :green_circle: Density

12_inventory_tab_density_1

12_inventory_tab_density_2

12_inventory_tab_density_3

#### :yellow_circle:  Sort fields

13_inventory_tab_sort_fields_1

13_inventory_tab_sort_fields_2

13_inventory_tab_sort_fields_3

**NOTE**: _When dragging the sort fields the background turns red but then they swap correctly_

#### :green_circle: Full screen

14_inventory_tab_full_screen

#### :green_circle: Column visibility

15_inventory_tab_column_visibility_1

15_inventory_tab_column_visibility_2


</details>


<details>
<summary>
:yellow_circle: Use export formatted control (export table to CSV button).
</summary>

16_inventory_tab_export_formated_button_1

16_inventory_tab_export_formated_button_1_A

16_inventory_tab_export_formated_button_2


**NOTE**: _Same error as in pagination_

</details>

<details>
<summary>
:green_circle: Click on the inspect document button and check the flyout functionality, the details must show the row clicked on the table
</summary>

17_inventory_tab_flyout

</details>

**Pull request merged**
