### PR TITLE
Replace discover Google cloud

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description
This PR, replaces the events tab on the Google cloud module
 
### Issues Resolved

- #6280 

### Evidence

image

# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |

- Apply filters using search bar input

<details>

</details>

- Apply filters using the search bar `add filter` feature

<details>

</details>

- Apply filters using the date picker

<details>

</details>

- Apply filters with no results (Check the `No results match your search criteria` message)

<details>

</details>

- Use the `saved queries` feature (Check saved queries CRUD)

<details>

</details>

## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |

- Check histogram chart hits consistency 

<details>

</details>

- Use chart options (three points: maximize, minimize, inspect) 

<details>

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |

- Check all table header features (sort, show/hide columns, density, etc)

<details>

</details>

- Check table pagination and rows per page

<details>

</details>

- Check document detail flyout

<details>

</details>

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Machi3mfl** [comment]
# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |

- Apply filters using search bar input

<details>




</details>

- Apply filters using the search bar `add filter` feature

<details>


</details>

- Apply filters using the date picker

<details>


</details>

- Apply filters with no results (Check the `No results match your search criteria` message)

<details>


</details>

- Use the `saved queries` feature (Check saved queries CRUD)

<details>


</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |

- Check histogram chart hits consistency 

<details>


</details>


- Use chart options (three points: maximize, minimize, inspect) 

<details>


</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |

- Check all table header features (sort, show/hide columns, density, etc)

<details>


</details>


- Check table pagination and rows per page

<details>


</details>

- Check document detail flyout

<details>


</details>

**Review by Machi3mfl — CHANGES_REQUESTED** [review]
# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :green_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :green_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :green_circle: | :black_circle: | :black_circle: |

- Apply filters using search bar input

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/06f5c686-73b3-403e-8145-ee125678349b

</details>

- Apply filters using the search bar `add filter` feature

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/5dae6aba-0fc8-4b15-906b-35e93bc1b4da

</details>

- Apply filters using the date picker

<details>


https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/c69446ae-2713-4d08-a34a-56760ec79f05


</details>

- Apply filters with no results (Check the `No results match your search criteria` message)

<details>


https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/fb247dba-e33a-48f1-8f80-1dbfc7b1738a

</details>

- Use the `saved queries` feature (Check saved queries CRUD)

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/e9bfc26f-9c13-4f17-9581-24164e674cee

</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :green_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :green_circle: | :black_circle: | :black_circle: |

- Check histogram chart hits consistency 

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/3414bc2a-fb28-42ed-80ee-4c95a7ba882b

</details>


- Use chart options (three points: maximize, minimize, inspect) 

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/0585a70b-e001-4c51-bb3b-12c9edc68f69

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :red_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :green_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :green_circle: | :black_circle: | :black_circle: |

- Check all table header features (sort, show/hide columns, density, etc)

<details>

Error when show all columns is clicked

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/7ca5fa8a-8c02-4966-9788-20fc31db20f6

Screenshot 2024-01-10 at 14 47 31

</details>


- Check table pagination and rows per page

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/bb95ad68-cd7e-4a31-ad3d-06bdb1b7034a

</details>

- Check document detail flyout

<details>


https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/5c71aaa6-6cd6-40b4-954a-1ee5d174aaa1

</details>

**Comment by JuanGarriuz** [comment]
# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |

<details><summary>Apply filters using search bar input</summary>

image

</details>

<details><summary>Apply filters using the search bar `add filter` feature</summary>


</details>

<details><summary>Apply filters using the date picker</summary>


</details>

<details><summary>Apply filters with no results (Check the `No results match your search criteria` message)</summary>


</details>

<details><summary>Use the `saved queries` feature (Check saved queries CRUD)</summary>


</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |

<details><summary>Check histogram chart hits consistency </summary>


</details>


<details><summary>Use chart options (three points: maximize, minimize, inspect) </summary>


</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |

<details><summary>Check all table header features (sort, show/hide columns, density, etc)</summary>


</details>


<details><summary>Check table pagination and rows per page</summary>


</details>

<details><summary>Check document detail flyout</summary>


</details>

**Comment by yenienserrano** [comment]
> # Tests
> ## Search bar
> Test	Chrome	Firefox	Safari
> Apply filters using search bar input	🟢	⚫	⚫
> Apply filters using the search bar `add filter` feature	🟢	⚫	⚫
> Apply filters using the date picker	🟢	⚫	⚫
> Apply filters with no results (Check the `No results match your search criteria` message)	🟢	⚫	⚫
> Use the `saved queries` feature (Check saved queries CRUD)	🟢	⚫	⚫
> * Apply filters using search bar input
> 
> * Apply filters using the search bar `add filter` feature
> 
> * Apply filters using the date picker
> 
> * Apply filters with no results (Check the `No results match your search criteria` message)
> 
> * Use the `saved queries` feature (Check saved queries CRUD)
> 
> ## Histogram chart
> Test	Chrome	Firefox	Safari
> Check histogram chart hits consistency	🟢	⚫	⚫
> Use chart options (three points: maximize, minimize, inspect)	🟢	⚫	⚫
> * Check histogram chart hits consistency
> 
> * Use chart options (three points: maximize, minimize, inspect)
> 
> ## Data grid
> Test	Chrome	Firefox	Safari
> Check all table header features (sort, show/hide columns, density, etc)	🔴	⚫	⚫
> Check table pagination and rows per page	🟢	⚫	⚫
> Check document detail flyout	🟢	⚫	⚫
> * Check all table header features (sort, show/hide columns, density, etc)
> 
> * Check table pagination and rows per page
> 
> * Check document detail flyout

the problem is fixed in this [PR](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6290)

**Comment by Machi3mfl** [comment]
### Tested the fixes made by @yenienserrano 

Screenshot 2024-02-16 at 14 37 42


https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/81500efc-564b-4522-9926-897809c89423

**Review by Machi3mfl — APPROVED** [review]

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!!

**Pull request merged**
