### PR TITLE
Fix design implementation

### PR DESCRIPTION
**Pull request by lucianogorza**
### Description
-  In the About page delete the API table and leave a React component the same as the previous Angular template.
-  Delete unused components related to the About page.
- In the UpdatesNotification component only ask for available updates if the user doesn't check "Disable update notifications".
- In API Table handle check updates button errors and show a toast.
 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard/issues/96

#### About page
image

#### Bottom bar notification
image

#### API Table
image

#### Updates status error message
image

#### Check updates button error
image

### Test

- Go to the About page and compare it to the current About page. They must be the same.
- When the bottom bar notification appears, check `Disable update notifications` and click the `Dismiss` button. Reload the page and check the network requests. A request for user preferences (ending in `/me`) should appear, but there should not be a request for available updates (ending in `/updates?checkAvailableUpdates=false`).
- Go to Settings -> API configuration. Disable the network connection and click on `Check Updates` button. A toast should appear with an error.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Tostti** [comment]
# Test

🟢 Go to the About page and compare it to the current About page. They must be the same.

image

🟢 When the bottom bar notification appears, check Disable update notifications and click the Dismiss button. Reload the page and check the network requests. A request for user preferences (ending in /me) should appear, but there should not be a request for available updates (ending in /updates?checkAvailableUpdates=false).

image


🟢 Go to Settings -> API configuration. Disable the network connection and click on Check Updates button. A toast should appear with an error.

image
image

**Review by Tostti — APPROVED** [review]
TEST:✔️
CR:✔️

LGTM

**Comment by asteriscos** [comment]
### API Settings Flyout

image

### Error and tooltips

image

### Check Updates button

image

### About page and bottom bar

image

### Dismiss notifications button

image

**Review by asteriscos — APPROVED** [review]
LGTM :heavy_check_mark:

**Pull request merged**
