### PR TITLE
Remove the vulnerability pattern check in the health check

### LINKED ISSUE #6395: Health-check vulnerabilities index-pattern validation should be removed
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 03 | Chrome, Firefox, Safari, etc |

**Description**
Currently, the health-check vulnerabilities index-pattern validation is disabled by default, but Wazuh manager has the vulnerabilities modules enabled by default, except when it's an upgraded installation. Therefore we need to contemplate several possible states in Wazuh Dashboard to ensure the vulnerabilities module can work properly.

These verifications will be made whenever a user accesses the vulnerabilities module, hence we need to make all the necessary checks in the vulnerabilities dashboard and inventory

**Expected Result**
1. The vulnerabilities index-pattern verification should be removed from the health-check
2. The vulnerabilities index-pattern verification configuration should be removed from the app settings
3. The proper validations will be made in the vulnerabilities module in this related issue
  - https://github.com/wazuh/wazuh-dashboard-plugins/issues/6394

**Screenshots**

screencapture-localhost-5601-app-app-settings-2024-02-08-16_30_24

Screenshot from 2024-02-08 16-30-57

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request removes the vulnerability pattern check in the health check and the related setting.

Changes:
  - Remove the vulnerability pattern check in the health check
  - Remove the setting `checks.vulnerabilities.pattern`

### Issues Resolved
#6395

### Evidence
image
image
```console
node@osd:~/kbn/data/wazuh/config$ grep checks wazuh.yml
# checks.api: true
# checks.fields: true
# checks.maxBuckets: true
# checks.metaFields: true
# checks.pattern: true
# checks.setup: true
# checks.template: true
# checks.timeFilter: true
```

### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| The check related to vulnerabilities shoud not appear in the health check | :black_circle: | :black_circle: | :black_circle: |
| The `checks.vulnerabilities.pattern` should not appear in the App Settings application | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: The check related to vulnerabilities shoud not appear in the health check</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: The `checks.vulnerabilities.pattern` should not appear in the App Settings application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

## Other

| Test | Result |
| --- |  --- |
| The `checks.vulnerabilities.pattern` should not appear in the initial configuration file | :black_circle: |

**Details**
<details>
<summary>:black_circle: The `checks.vulnerabilities.pattern` should not appear in the initial configuration file</summary>

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

screencapture-localhost-5601-app-app-settings-2024-02-09-13_41_52

**Comment by JuanGarriuz** [comment]
### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| The check related to vulnerabilities shoud not appear in the health check | 🟢  | :black_circle: | :black_circle: |
| The `checks.vulnerabilities.pattern` should not appear in the App Settings application | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary> 🟢  The check related to vulnerabilities shoud not appear in the health check</summary>

Chrome - 🟢 

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>🟢 The `checks.vulnerabilities.pattern` should not appear in the App Settings application</summary>

Chrome - 🟢 

image



Firefox - :black_circle:

Safari - :black_circle:

</details>


## Other

| Test | Result |
| --- |  --- |
| The `checks.vulnerabilities.pattern` should not appear in the initial configuration file | 🟢  |

**Details**
<details>
<summary> 🟢  The `checks.vulnerabilities.pattern` should not appear in the initial configuration file</summary>

image

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Review by lucianogorza — APPROVED** [review]
### CR 🟢 
### Test 🟢 
image
image

**Pull request merged**
