### PR TITLE
Use index pattern id instead of title

### PR DESCRIPTION
**Pull request by lucianogorza**
### Description
This PR resolves the issue where dashboards do not filter correctly when selecting an index pattern with an ID different from its name. The solution involves updating the application to use the index pattern ID instead of the title.

#### Changes
- Modified the application to use the index pattern ID for filtering in dashboards.
 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6742

### Evidence

image
image
image
image

### Test
1. Create an index pattern with an ID that differs from its name.
2. Navigate to the top bar selector and select the newly created index pattern.
3. Verify the following cases:

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Threat Hunting Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Threat Hunting Events tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Generate PDF report from Threat Hunting | :black_circle: | :black_circle: | :black_circle: |
| Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Vulnerability Detection Events tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Threat Hunting Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Threat Hunting Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Generate PDF report from Threat Hunting</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Vulnerability Detection Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by asteriscos** [comment]
| Test | Chrome | 
| --- |  --- | 
| Threat Hunting Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | 
| Threat Hunting Events tab -> Check fixed filters and data are consistent | :black_circle: | 
| Generate PDF report from Threat Hunting | :black_circle: | 
| Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | 
| Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent | :black_circle: | 
| Vulnerability Detection Events tab -> Check fixed filters and data are consistent | :black_circle: | 

**Details**
<details>
<summary>:black_circle: Threat Hunting Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:





</details>

<details>
<summary>:black_circle: Threat Hunting Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:





</details>

<details>
<summary>:black_circle: Generate PDF report from Threat Hunting</summary>

Chrome - :black_circle:





</details>

<details>
<summary>:black_circle: Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:





</details>

<details>
<summary>:black_circle: Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:





</details>

<details>
<summary>:black_circle: Vulnerability Detection Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:





</details>

**Comment by yenienserrano** [comment]
| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Threat Hunting Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Threat Hunting Events tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Generate PDF report from Threat Hunting | :black_circle: | :black_circle: | :black_circle: |
| Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |
| Vulnerability Detection Events tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Threat Hunting Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Threat Hunting Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Generate PDF report from Threat Hunting</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Vulnerability Detection Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by yenienserrano — APPROVED** [review]
CR: 🟢 
Test: 🟢

**Comment by Desvelao** [comment]
| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Threat Hunting Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :green_circle: |
| Threat Hunting Events tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :green_circle: |
| Generate PDF report from Threat Hunting | :black_circle: | :black_circle: | :green_circle: |
| Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :green_circle: |
| Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :green_circle: |
| Vulnerability Detection Events tab -> Check fixed filters and data are consistent | :black_circle: | :black_circle: | :green_circle: |

**Details**
<details>
<summary>:green_circle: Threat Hunting Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Threat Hunting Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Generate PDF report from Threat Hunting</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Vulnerability Detection Dashboard tab -> Check fixed filters and data are consistent</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:


</details>

<details>
<summary>:green_circle: Vulnerability Detection Inventory tab -> Check fixed filters and data are consistent</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Vulnerability Detection Events tab -> Check fixed filters and data are consistent</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Pull request merged**
