### PR TITLE
Remove management AngularJS controllers

### LINKED ISSUE #6549: [Remove discover] Refactor AngularJS of management
# Description

To deprecate angularJS in the plugins we need to refactor the tools and dev tools controllers into a ReactJS component.
The files are located in:
- _/plugins/main/public/controllers/management/management.js_

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request removes the tools and dev tools AngularJS controllers.

Changes:
- Remove AngularJS controller of Management
  - Remove deprecated listeners
  - Remove deprecated methods
  - Remove logtestProps from some components that were passed from the
    AngularJS controller
    - Move some methods to ReactJS
- Create router to manage the view to display
- Change button to render the Ruleset Test or Decoders Test to use a
  button that opens a flyout.
- Remove the flyout components in the Logtest component

> [!WARNING]  
> This pull request depends on https://github.com/wazuh/wazuh-dashboard-plugins/issues/6532.

### Issues Resolved
#6549

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the Server management > Ruleset Test is rendered correctly | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Ruleset Test button on Decoders/Rules >  Add new file opens a flyout with the content of Ruleset Test | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Groups displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Status displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Cluster displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Statistics displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Logs displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Configuration displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > CDB Lists displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Decoders displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Rules displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Dashboard Management > Reporting displays the view | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the Server management > Ruleset Test is rendered correctly</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Ruleset Test button on Decoders/Rules >  Add new file opens a flyout with the content of Ruleset Test</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Groups displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Status displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Cluster displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Statistics displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Logs displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Configuration displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > CDB Lists displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Decoders displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Rules displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Dashboard Management > Reporting displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the Server management > Ruleset Test is rendered correctly | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Ruleset Test button on Decoders/Rules >  Add new file opens a flyout with the content of Ruleset Test | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Groups displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Status displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Cluster displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Statistics displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Logs displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Configuration displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > CDB Lists displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Decoders displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Rules displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Ruleset Test displays the view | :green_circle: | :black_circle: | :black_circle: |
| Ensure the Dashboard Management > Reporting displays the view | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the Server management > Ruleset Test is rendered correctly</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Ruleset Test button on Decoders/Rules >  Add new file opens a flyout with the content of Ruleset Test</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Groups displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Status displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Cluster displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Statistics displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Logs displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Configuration displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > CDB Lists displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Decoders displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Rules displays the view</summary>

Chrome - :green_circle:

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Server Management > Ruleset Test displays the view</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the Dashboard Management > Reporting displays the view</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Comment by lucianogorza** [comment]
## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the Server management > Ruleset Test is rendered correctly | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Ruleset Test button on Decoders/Rules >  Add new file opens a flyout with the content of Ruleset Test | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Groups displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Status displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Cluster displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Statistics displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Logs displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Configuration displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > CDB Lists displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Decoders displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Server Management > Rules displays the view | :black_circle: | :black_circle: | :black_circle: |
| Ensure the Dashboard Management > Reporting displays the view | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the Server management > Ruleset Test is rendered correctly</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Ruleset Test button on Decoders/Rules >  Add new file opens a flyout with the content of Ruleset Test</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Groups displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Status displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Cluster displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Statistics displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Logs displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Configuration displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > CDB Lists displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Decoders displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Server Management > Rules displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the Dashboard Management > Reporting displays the view</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by lucianogorza — APPROVED** [review]
LGTM

**Review by JuanGarriuz — APPROVED** [review]

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
