### PR TITLE
Add manager filter with cluster mode disabled

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
This pull request changes the field name that the Vulnerabilities module uses to pre-filter the cluster or manager selected by the Wazuh API dropdown.

 
### Issues Resolved

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6407

### Evidence
image

### Test

- Verify the implicit filter uses the field `wazuh.cluster.name` and the configured cluster name in Dashboard and Inventory tabs when the cluster mode is enabled
- Verify the implicit filter uses the field `wazuh.manager.name` and the value is the manager name in Dashboard and Inventory tabs when the cluster mode is disabled

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verify the implicit filter uses the field wazuh.cluster.name and the configured cluster name in Dashboard and Inventory tabs when the cluster mode is enabled | :black_circle: | :black_circle: | :black_circle: |
| Verify the implicit filter uses the field wazuh.manager.name and the value is the manager name in Dashboard and Inventory tabs when the cluster mode is disabled | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Verify the implicit filter uses the field wazuh.cluster.name and the configured cluster name in Dashboard and Inventory tabs when the cluster mode is enabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Verify the implicit filter uses the field wazuh.manager.name and the value is the manager name in Dashboard and Inventory tabs when the cluster mode is disabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verify the implicit filter uses the field wazuh.cluster.name and the configured cluster name in Dashboard and Inventory tabs when the cluster mode is enabled | :green_circle: | :black_circle: | :black_circle: |
| Verify the implicit filter uses the field wazuh.manager.name and the value is the manager name in Dashboard and Inventory tabs when the cluster mode is disabled | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Verify the implicit filter uses the field wazuh.cluster.name and the configured cluster name in Dashboard and Inventory tabs when the cluster mode is enabled</summary>

Chrome - :green_circle:
image
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Verify the implicit filter uses the field wazuh.manager.name and the value is the manager name in Dashboard and Inventory tabs when the cluster mode is disabled</summary>

Chrome - :green_circle:
image
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
# Minor finding

In my testing I found if I changed to enable or disable the cluster and access to the `Vulnerabilities Detection` application, it used the related filter to the previous state of the cluster status.

This seems to be caused because the state used to decide what filter should be added to the search bar is updated after the filter is added.

**Review by Desvelao — APPROVED** [review]
LGTM!

**Comment by lucianogorza** [comment]
## CR 🟢 
## Test 🟢 

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verify the implicit filter uses the field wazuh.cluster.name and the configured cluster name in Dashboard and Inventory tabs when the cluster mode is enabled |🟢 | :black_circle: | :black_circle: |
| Verify the implicit filter uses the field wazuh.manager.name and the value is the manager name in Dashboard and Inventory tabs when the cluster mode is disabled | 🟢 | :black_circle: | :black_circle: |

**Details**
<details>
<summary>🟢 Verify the implicit filter uses the field wazuh.cluster.name and the configured cluster name in Dashboard and Inventory tabs when the cluster mode is enabled</summary>

Chrome - 🟢
image
image
image


</details>

<details>
<summary>🟢 Verify the implicit filter uses the field wazuh.manager.name and the value is the manager name in Dashboard and Inventory tabs when the cluster mode is disabled</summary>

Chrome - 🟢

image
image
image

</details>

**Review by lucianogorza — DISMISSED** [review]
LGTM

**Review by lucianogorza — APPROVED** [review]

**Pull request merged**
