### PR TITLE
Shown Wazuh API version is wrong or empty after upgrade

### PR DESCRIPTION
**Pull request by guidomodarelli**
### Description

During https://github.com/wazuh/wazuh/issues/27183, it was found that Wazuh API version shown is not the current one after upgrading from v4.9.2 to v4.10.0-rc1

image

After cleaning the cache, the error is worse

image

**Expected behavior**

Wazuh API is v4.10.0

image

### Issues Resolved

Closes https://github.com/wazuh/wazuh-dashboard/issues/440

### Evidence

image

image

image

image

### Test

1. Navigate to `Dashboard management` » `Server APIs`
2. Open DevTools
3. Go to `Application` » `Session storage`
4. Delete key `checkUpdates`
  image
5. Reload the page
6. Please verify the status of the `Version` column under two scenarios: when everything is correct and when an issue arises.

> [!NOTE]
> Remove `checkUpdates` for each reloaded page.

#### Unit tests

image

### Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Tostti — APPROVED** [review]
Test 🟢 

Tested in a pre-release environment, replacing the original plugins with new ones generated based on this branch
imagen

CR 🟢 

LGTM

**Review by Tostti — CHANGES_REQUESTED** [review]
A test  in `get-updates.test.ts` is failing after this change 

```
 FAIL  server/services/updates/get-updates.test.ts

 RUNS  ...




  ● getUpdates function › should return available updates from api

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 5

    @@ -1,10 +1,12 @@
      Object {
        "apis_available_updates": Array [
          Object {
            "api_id": "api id",
    -       "current_version": "4.3.1",
    +       "current_version": "vundefined",
    +       "last_available_major": undefined,
    +       "last_available_minor": undefined,
            "last_available_patch": Object {
              "description": "## Manager
    
      
    
      ### Fixed
    
      
    
    @@ -16,10 +18,12 @@
                "patch": 8,
              },
              "tag": "v4.3.8",
              "title": "Wazuh v4.3.8",
            },
    +       "last_check_date": undefined,
            "status": "availableUpdates",
    +       "update_check": undefined,
          },
        ],
        "last_check_date": Any<Date>,
      }

      137 |     const updates = await getUpdates(true);
      138 |
    > 139 |     expect(updates).toEqual({
          |                     ^
      140 |       last_check_date: expect.any(Date),
      141 |       apis_available_updates: [
      142 |         {

      at Object.<anonymous> (server/services/updates/get-updates.test.ts:139:21)
      ```

**Comment by Desvelao** [comment]
# Test
image
image

@chantal-kelm found the `Version` column does not appear if `wazuh.updates.disabled: true` is enabled. I think the `Version` column should appear always. That value can be retrieved (as it is done in this pull request) from the Wazuh server API.

**Review by Tostti — DISMISSED** [review]
Test 🟢 
imagen

CR 🟢 

LGTM

**Pull request merged**
