### PR TITLE
Fix error generating dashboard reports on Firefox

### LINKED ISSUE #6900: Generate PDF report button doesn't work in Firefox
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 06 | Firefox |

**Description**
When using a Firefox browser the create PDF report doesn't work, and throws an error.

**Preconditions**
1. Use Firefox

**Steps to reproduce**
1. Navigate to any dashboard
2. Click on Generate report
3. See the error

**Screenshots**

Peek 2024-08-06 21-21

image

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request fixes an error generating the dashboard reports using the Firefox web browser.

Changes:
- Add an embedded and customized `dom-to-image-more` (v3.3.1) dependency
- Replace the library to generate de screenshots of the dashboard
  visualizations
- Apply a fix related to cropped screenshots on Firefox
- Remove embedded `dom-to-image` dependency
- Change KPIs visualization label color when generating a report on dark mode (platform theme)
 
### Issues Resolved
#6900

### Evidence

Firefox
- Amazon Web Services:
image
image
image

- Threat Hunting
image
image
image

Google Chrome

- Amazon Web Services
image
image
image

- Threat Hunting
image
image
image

### Test

**IMPORTANT**: Test acceptance criteria: test with Google Chrome (or variant), Firefox and Safari.

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to the Malware Detection > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the File Integrity Monitoring > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Threat Hunting > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the MITRE ATT&CK > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the VirusTotal > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the PCI DSS > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the GDPR > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the HIPAA > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the NIST 800-53 > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the TSC > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Docker > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Amazon Web Services > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Google Cloud > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the GitHub > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Office 365 > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Go to the Malware Detection > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the File Integrity Monitoring > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Threat Hunting > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the MITRE ATT&CK > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the VirusTotal > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the PCI DSS > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the GDPR > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the HIPAA > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the NIST 800-53 > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the TSC > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Docker > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Amazon Web Services > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Google Cloud > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the GitHub > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Office 365 > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by chantal-kelm** [comment]
**Chrome**

https://github.com/user-attachments/assets/66a2c08f-a6f8-438f-9d41-e89783a32f16

**Firefox**

https://github.com/user-attachments/assets/d826400f-05c3-4f6a-895a-6a14780010f0

Dark mode 🔴 

Captura de pantalla 2024-08-08 a la(s) 11 20 05 a  m

The table does not look complete, for example in FIM 🔴 

Captura de pantalla 2024-08-08 a la(s) 11 19 38 a  m

**Safari**

https://github.com/user-attachments/assets/1b44039d-7a2b-4297-b2c1-edc7a2b10fe8

**Comment by Desvelao** [comment]
I will try to research what is happening on dark mode, but there is an issue that could be related: https://github.com/wazuh/wazuh-dashboard-plugins/issues/3805

The visualization included on the PDF reports does not include the table of `Threat Hunting`. The table visible on the report is a summary, that is obtained on the backend side.

The quality of the visualization could be related to taking the screenshot. I initially added some code that scaled the visualization x2 and this had more resolution on the report, but using this approach causes a problem with the visualization related with KPIs. This was seen with @yenienserrano.

**Comment by Desvelao** [comment]
Findings on https://github.com/wazuh/wazuh-dashboard-plugins/pull/6902#issuecomment-2275999041

- PDF report background displays dark color:
This could be caused by the browser configuration. Maybe it is inverting the colors.

- The label of KPIs visualization are displayed with lighter colors when generating the report in dark mode of the platform.
I will add a fix to solve this problem.

- The table releated to FIM report is cropped
This could happen with others tables and depends on the row content. This will not be fixed on this pull request and we should open another issue for this topic.

-

**Comment by yenienserrano** [comment]
### Test

**IMPORTANT**: Test acceptance criteria: test with Google Chrome (or variant), Firefox and Safari.

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to the Malware Detection > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the File Integrity Monitoring > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Threat Hunting > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the MITRE ATT&CK > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the VirusTotal > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the PCI DSS > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the GDPR > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the HIPAA > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the NIST 800-53 > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the TSC > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Docker > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Amazon Web Services > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Google Cloud > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the GitHub > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |
| Go to the Office 365 > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Go to the Malware Detection > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the File Integrity Monitoring > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Threat Hunting > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the MITRE ATT&CK > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the VirusTotal > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the PCI DSS > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the GDPR > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the HIPAA > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the NIST 800-53 > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the TSC > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Docker > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Amazon Web Services > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Google Cloud > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the GitHub > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to the Office 365 > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by yenienserrano — DISMISSED** [review]
LGTM

**Comment by chantal-kelm** [comment]
| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to the Malware Detection > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the File Integrity Monitoring > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the Threat Hunting > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the MITRE ATT&CK > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the VirusTotal > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the PCI DSS > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the GDPR > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the HIPAA > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :yellow_circle: | :black_circle: | :black_circle: |
| Go to the NIST 800-53 > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the TSC > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the Docker > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the Amazon Web Services > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the Google Cloud > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the GitHub > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |
| Go to the Office 365 > Dashboard and generate a report. It should contain the visualizations with an acceptable render | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Go to the Malware Detection > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/da2150d7-1ecf-4e46-a62a-58e9c1cc25d5

</details>

<details>
<summary>:green_circle: Go to the File Integrity Monitoring > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/4a0f0be1-ad0a-4760-a1e7-0a07275cf5cf

</details>

<details>
<summary>:green_circle: Go to the Threat Hunting > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/ec23aa6d-74ad-4d2e-bf29-630e7370effc

</details>

<details>
<summary>:green_circle: Go to the MITRE ATT&CK > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/943f8e96-4bd1-4e17-8c86-f227d05c4176

</details>

<details>
<summary>:green_circle: Go to the VirusTotal > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/738c5ae8-eb42-4bf2-b64f-9bd053dfa084

</details>

<details>
<summary>:green_circle: Go to the PCI DSS > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/8f74c9b0-b06b-462c-bfc1-13ee9711fed2

</details>

<details>
<summary>:green_circle: Go to the GDPR > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/8bd6511f-1811-4f78-869f-afef9e498bb3

</details>

<details>
<summary>:green_circle: Go to the HIPAA > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :yellow_circle:

https://github.com/user-attachments/assets/fe846a8d-3de7-4d33-8f1d-2eeaa5c8dfd7

### The metric text colour is not very visible in dark mode:
Captura de pantalla 2024-08-09 a la(s) 1 20 53 p  m

</details>

<details>
<summary>:green_circle: Go to the NIST 800-53 > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/93d77ea3-5f9a-4e81-bb7f-45b12964ff9b

### The metric text colour is not very visible in dark mode:
Captura de pantalla 2024-08-09 a la(s) 1 27 34 p  m

Captura de pantalla 2024-08-09 a la(s) 1 27 48 p  m

</details>

<details>
<summary>:green_circle: Go to the TSC > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/d8630992-5683-43a9-9bb6-f7fc50c93db6

</details>

<details>
<summary>:green_circle: Go to the Docker > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/b4697d4d-a88e-4f79-be15-6e28533df38e

</details>

<details>
<summary>:green_circle: Go to the Amazon Web Services > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/8f64f6c7-de11-47b8-ac90-aede3e0557f5

</details>

<details>
<summary>:green_circle: Go to the Google Cloud > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/f4b00242-2e6d-4115-90be-3e96a301ed7e

</details>

<details>
<summary>:green_circle: Go to the GitHub > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/a649b4f7-9b1f-440e-b408-852fa0232f46

</details>

<details>
<summary>:green_circle: Go to the Office 365 > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/32de0979-9dc3-4ad6-8457-aa5320a31ab9

</details>

**Comment by Desvelao** [comment]
# Changes

Fixed colors on visualization that caused poorly render on the reports

- HIPAA
image

- NIST 800-53
  - Unpinned agent
  image
  
  - Pinned agent
image

- Remove unused code related to TSC visualization

**Review by chantal-kelm — DISMISSED** [review]
CR: ✅ 
TEST: ✅ 

<details>
<summary>:green_circle: Go to the HIPAA > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:


https://github.com/user-attachments/assets/c7288ff2-975e-47ae-871e-e11ef916bf81

### The metric text colour is not very visible in dark mode:

Captura de pantalla 2024-08-13 a la(s) 7 16 21 a  m

</details>

<details>
<summary>:green_circle: Go to the NIST 800-53 > Dashboard and generate a report. It should contain the visualizations with an acceptable render</summary>

Chrome - :green_circle:

https://github.com/user-attachments/assets/e2324aed-5654-460a-b372-c8c28657190b

### The metric text colour is not very visible in dark mode:

Captura de pantalla 2024-08-13 a la(s) 7 17 55 a  m

Captura de pantalla 2024-08-13 a la(s) 7 18 12 a  m

</details>

**Review by yenienserrano — DISMISSED** [review]

**Pull request merged**
