### PR TITLE
Implement embeddable dashboard on GDPR

### LINKED ISSUE #6505: [Remove discover] Implement embeddable dashboard on GDPR module
## Description

We have to implement the embeddable dashboard on GDPR -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Implement the embeddable dashboard on GDPR -> `Dashboard` tab
- [x] Implement the embeddable dashboard on GDPR -> `Controls` tab
- [x] Implement the embeddable dashboard on GDPR -> `Events` tab

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request replaces the `Dashboard` and adapts the `Controls` tab on the GDPR application.

Other changes:
- Fix repeated request on Regulatory compliance > Controls > flyout and MITRE ATT&CK > Framework > flyout
 
### Issues Resolved
#6505

### Evidence
image
image
image

### Test
Go to GDPR > Dashboard:

Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.
The visualizations have to be updated according to the filters applied in the searchbar.
The visualizations have to be updated when a search is performed in the searchbar.
If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
If there is SampleData, the corresponding SampleData message must appear.
If an agent is pinned, the views must be updated and changed to the agent view, if applicable.
Check filter behavior with respect to hide alerts, allow agents and filter order.

Go to GDPR > Controls
Check the requirements filters on the on the left side filters the requirements on the right side
Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.
In the details flyout click on the show on dashboard and events links, they should display this tabs with a filter related to the selected requirement
The link on the flyout table should redirect to Endpoint Summary and Rules respectively

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
I found repeated filters on the discover table of `Controls` > `flyout`. This is happening in all the apps related to regulatory compliance and MITRE ATT&CK.

image

This should not be a reason to block the pull request. We will review this problem later.

**Review by lucianogorza — COMMENTED** [review]
## CR ⚫   
## Test ⚫

### Dashboard

- [ ] Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.

<details><summary>Details</summary>


</details>

- [ ] The visualizations have to be updated according to the filters applied in the searchbar.

<details><summary>Details</summary>


</details>

- [ ] The visualizations have to be updated when a search is performed in the searchbar.

<details><summary>Details</summary>


</details>

- [ ] If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.

<details><summary>Details</summary>


</details>

- [ ] If there is SampleData, the corresponding SampleData message must appear.

<details><summary>Details</summary>


</details>

- [ ] If an agent is pinned, the views must be updated and changed to the agent view, if applicable.

<details><summary>Details</summary>


</details>

- [ ] Check filter behavior with respect to hide alerts, allow agents and filter order.

<details><summary>Details</summary>

### Hide manager alerts: false


### Hide manager alerts: true


</details>

### Controls

Go to PCI DSS > Controls

- [ ] Check the requirements filters on the on the left side filters the requirements on the right side

<details><summary>Details</summary>


</details>

- [ ] 🟡 Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.

<details><summary>Details</summary>


🟡 When the flyout is opened, the query is repeated. **The error is not responsibility of the PR.**


</details>

- [ ] In the details flyout click on the show on dashboard and events links, they should display this tabs with a filter related to the selected requirement

<details><summary>Details</summary>

### Dashboard link


### Events link


</details>

- [x] The link on the flyout table should redirect to Endpoint Summary and Rules respectively

<details><summary>Details</summary>

### Agent

### Rule

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Comment by asteriscos** [comment]
## CR ⚫   
## Test ⚫

### Dashboard

:green_circle: Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.

<details><summary>Details</summary>

Peek 2024-05-13 12-49


</details>

:green_circle: The visualizations have to be updated according to the filters applied in the searchbar.

<details><summary>Details</summary>

Peek 2024-05-13 12-50


</details>

:green_circle: The visualizations have to be updated when a search is performed in the searchbar.

<details><summary>Details</summary>

Peek 2024-05-13 12-52


</details>

:green_circle: If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.

<details><summary>Details</summary>

image


</details>

:green_circle: If there is SampleData, the corresponding SampleData message must appear.

<details><summary>Details</summary>

image


</details>

:green_circle: If an agent is pinned, the views must be updated and changed to the agent view, if applicable.

<details><summary>Details</summary>

Peek 2024-05-13 12-53


</details>

:green_circle: Check filter behavior with respect to hide alerts, allow agents and filter order.

<details><summary>Details</summary>

### Hide manager alerts: false

image


### Hide manager alerts: true

image


</details>

### Controls

Go to PCI DSS > Controls

:green_circle: Check the requirements filters on the on the left side filters the requirements on the right side

<details><summary>Details</summary>

image


</details>

:green_circle: Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.

<details><summary>Details</summary>

image



</details>

:green_circle: In the details flyout click on the show on dashboard and events links, they should display these tabs with a filter related to the selected requirement

<details><summary>Details</summary>

### Dashboard link

Peek 2024-05-13 13-06


### Events link

Peek 2024-05-13 13-06


</details>

:green_circle: The link on the flyout table should redirect to Endpoint Summary and Rules respectively

<details><summary>Details</summary>

### Agent

Peek 2024-05-13 13-08


### Rule

Peek 2024-05-13 13-09


</details>

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
