### PR TITLE
Add - when run as is disable

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description

A - is added when the run as is disabled, and a tooltip with information is added
 
### Issues Resolved

- #6351

### Evidence

image

### Test

1. Navigate to Indexer/Dashboard Management -> Server API
2. Review the column "Run as"

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by lucianogorza** [comment]
## Test 🟢 

### Run as: false
image

### Run as: true
image

**Review by lucianogorza — APPROVED** [review]
## CR 🟢 
## Test 🟢 

### Run as: false
image

### Run as: true
image

**Review by Tostti — APPROVED** [review]
# Test
image
image

Test ✅ 
CR ✅ 

LGTM

**Review by Tostti — APPROVED** [review]
LGTM

**Pull request merged**
