### PR TITLE
Hide vulnerabilities global filter editor button

### LINKED ISSUE #6654: Inconsistent wazuh.cluster.name filter
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | RC1 | Any |

**Description**

The default setting for the vulnerability detection dashboard incorporates a filter labeled wazuh.cluster.name set to the value "wazuh1". Initially, it appears this filter is not intended for modification. However, it is possible to deactivate this filter and apply negation by accessing the "Change all filters" menu.

**Preconditions**
1. Full environment with Vulnerability detection enabled

**Steps to reproduce**
 1. Go to Vulnerability Detection > Inventory
 2. Using "Change all filters" negate the wazuh.cluster.name filter
 3. Go to Vulnerability Deteciton > Dashboard
 4. Check that dashboard is not working as expected. In addition, cluster filter now is not negated.

**Expected Result**
1. Use should not be able to edit `wazuh.cluster.name`  filter

**Actual Result**
1. Wazuh.cluster.name filter can be edit, leading into inconsistent dashboard

**Screenshots**
image

**Video**

[filter_inconsistent.webm](https://github.com/wazuh/wazuh/assets/11089305/a9d5f444-349e-4e2a-af64-6f3085ea9f67)

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
This pull request hides the global filter editor button in the Vulnerabilities dashboard and inventory tab. This prevents the user from disabling implicit filters.

image

 
### Issues Resolved
Closes #6654

### Evidence

image

image

### Test
- Go to _Threat Intelligence / Vulnerability detector / Dashboard_
- Verify the global filter editor is hidden
- Go to _Threat Intelligence / Vulnerability detector / Inventory_
- Verify the global filter editor is hidden

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# Test :green_circle: 

image
image

**Review by Desvelao — APPROVED** [review]
LGTM!

**Review by jbiset — APPROVED** [review]
## CR: :green_circle: 

## Test UI: :green_circle: 

### Chrome :green_circle: 

image

image

### Firefox :green_circle: 

image

image

**Review by yenienserrano — APPROVED** [review]
LGTM 

Chrome
image

image


Safari

image

image

**Pull request merged**
