### PR TITLE
Add Docker envs for 4.6.x and 4.7.x pre-release and release and add server to osd-dev environment

### PR DESCRIPTION
**Pull request by AlexRuiz7**
### Description
This PR adds the Docker environments a real server to the osd-dev environments and pre-release and release environments for 4.6.x and 4.7.x.

Changes:

- Add real server to `osd-dev` environments that is enabled through the server profile
- Fix pre-release and release environments for 4.6.x
- Add pre-release and release environments for 4.7.x
  
### Issues Resolved
None

### Tests

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## Other

| Test | Result |
| --- |  --- |
| Deploy a standard osd-dev environment and this should work correctly | :black_circle: |
| Deploy a saml osd-dev environment and this should work correctly | :black_circle: |
| Deploy a server osd-dev environment and this should work correctly | :black_circle: |
| Deploy a 4.6.x pre-release environment and this should work correctly | :black_circle: |
| Deploy a 4.6.x release environment and this should work correctly | :black_circle: |
| Deploy a 4.7.x pre-release environment and this should work correctly | :black_circle: |
| Deploy a 4.7.x release environment and this should work correctly | :black_circle: |

**Details**
<details>
<summary>:black_circle: Deploy a standard osd-dev environment and this should work correctly</summary>

</details>

<details>
<summary>:black_circle: Deploy a saml osd-dev environment and this should work correctly</summary>

</details>

<details>
<summary>:black_circle: Deploy a server osd-dev environment and this should work correctly</summary>

</details>

<details>
<summary>:black_circle: Deploy a 4.6.x pre-release environment and this should work correctly</summary>

</details>

<details>
<summary>:black_circle: Deploy a 4.6.x release environment and this should work correctly</summary>

</details>

<details>
<summary>:black_circle: Deploy a 4.7.x pre-release environment and this should work correctly</summary>

</details>

<details>
<summary>:black_circle: Deploy a 4.7.x release environment and this should work correctly</summary>

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by asteriscos** [comment]
| Test | Result |
| --- |  --- |
| Deploy a standard osd-dev environment and this should work correctly | :green_circle: |
| Deploy a saml osd-dev environment and this should work correctly | :black_circle: |
| Deploy a server osd-dev environment and this should work correctly | :green_circle: |
| Deploy a 4.6.x pre-release environment and this should work correctly | :green_circle: |
| Deploy a 4.6.x release environment and this should work correctly | :green_circle: |
| Deploy a 4.7.x pre-release environment and this should work correctly | :black_circle: |
| Deploy a 4.7.x release environment and this should work correctly | :black_circle: |

**Review by asteriscos — APPROVED** [review]

**Comment by Tostti** [comment]
| Test | Result |
| --- |  --- |
| Deploy a **standard** osd-dev environment and this should work correctly | :green_circle: |
| Deploy a **saml** osd-dev environment and this should work correctly | :black_circle: |
| Deploy a **server** osd-dev environment and this should work correctly | :black_circle: |
| Deploy a **4.6.x pre-release** environment and this should work correctly |:black_circle:: |
| Deploy a **4.6.x release** environment and this should work correctly | :black_circle: |
| Deploy a **4.7.x pre-release** environment and this should work correctly | :black_circle: |
| Deploy a **4.7.x release** environment and this should work correctly | :black_circle: |

**Review by Tostti — DISMISSED** [review]

**Review by Tostti — APPROVED** [review]
Test ✅ 

| Test | Result |
| --- |  --- |
| Deploy a **standard** osd-dev environment and this should work correctly | :green_circle: |
| Deploy a **saml** osd-dev environment and this should work correctly | :green_circle: |
| Deploy a **server** osd-dev environment and this should work correctly | :green_circle: |
| Deploy a **4.6.x pre-release** environment and this should work correctly |:green_circle: |
| Deploy a **4.6.x release** environment and this should work correctly | :green_circle: |
| Deploy a **4.7.x pre-release** environment and this should work correctly | :green_circle: |
| Deploy a **4.7.x release** environment and this should work correctly | :green_circle: |

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

image

**Pull request merged**
