### PR TITLE
Fixed adding the same filter twice doesn't show it in the search bar.

### PR DESCRIPTION
**Pull request by JuanGarriuz**
### Description

A timestamp has been added to handle when the same filter is added twice.

### Issues Resolved

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7124

### Evidence

https://github.com/user-attachments/assets/b42cedaf-6cc3-4f66-ba4d-a8db2158c62d

### Test

Check that adding a filter through the details flyout, deleting into the search-bar, and adding the same filter again, renders in the input of the search-bar.

### Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by chantal-kelm — COMMENTED** [review]
The use case works correctly but it would be nice to fix the following error in console:

> Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
> Element with focus: button
> Ancestor with aria-hidden

https://github.com/user-attachments/assets/b116e88b-d7c2-4928-a946-19f6e5586e37

**Review by guidomodarelli — DISMISSED** [review]
Legend:
⚫ 🠊 The test hasn't started yet.
🟢 🠊 All checks passed.
🟡 🠊 There is at least one expected fail or skipped test and no failures.
🔴 🠊 There is at least one failed check.
⚪ 🠊 Doesn't apply.
🔧 🠊 Request changes. 

CR 🟢
TEST 🟢


https://github.com/user-attachments/assets/2161859f-974f-4748-b0e7-9b3c164b71e4

**Review by chantal-kelm — APPROVED** [review]
LGTM

**Review by chantal-kelm — APPROVED** [review]
LGTM

**Review by guidomodarelli — APPROVED** [review]
LGTM

**Review by asteriscos — COMMENTED** [review]
CR: :green_circle:

**Pull request merged**
