### PR TITLE
Replace the plugin logging system by the provided by the platform

### PR DESCRIPTION
**Pull request by Desvelao**
### Description

This pull request replaces the custom logging service with the one provided by the platform.

Changes:
- Add the `wazuhCore` plugin as dependency of `main`
- Remove the `logs.level` setting
- Replace the custom logging service with the one provided by the platform
  - Remove BaseLogger, log and uiLogger services
  - Create scoped server platform loggers with tags
  - Remove unused `winston` dependency used by the custom logger
    - `yarn.lock` files were updated
- Move some services from the main to the core plugin, adapt its usage, and replace the logging service
  - CacheAPIUserAllowRunAs
  - ManageHosts
  - ServerAPIClient (aka api-interceptor)
  - ServerAPIHostEntries (aka manage-hosts)
  - UpdateConfigurationFile
  - UpdateRegistry
  - dashboardSecurity (aka SecurityObj)
- Added some logs to server side
- Remove constants that define the path to log files
- Remove `App logs` application
- Remove API endpoint
  - GET /utils/logs/ui (unused by the frontend side)
  - GET /utils/logs
- Remove unused code
- Replace the usage of endpoint controllers to get data in the statistics and monitoring by core services

### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6137

### Evidence

Logs starting the platform:
```
server    log   [10:16:58.708] [info][initialize][plugins][wazuh] Wazuh dashboard index: .kibana
server    log   [10:16:58.708] [info][initialize][plugins][wazuh] App revision: 00
server    log   [10:16:58.714] [info][initialize][plugins][wazuh] Total RAM: 15922MB
server    log   [10:17:00.310] [info][initialize][plugins][wazuh] Configuration registry saved.
server    log   [10:17:00.358] [error][data][opensearch] [ResponseError]: Response Error
server    log   [10:17:00.360] [error][data][opensearch] [ResponseError]: Response Error
server    log   [10:17:00.469] [info][monitoring][plugins][wazuh] Updated the wazuh-agent template
server    log   [10:17:00.594] [info][listening] Server running at https://0.0.0.0:5601
server    log   [10:17:00.745] [info][cron-scheduler][plugins][wazuh] Updated the wazuh-statistics template
server    log   [10:17:00.763] [info][server][OpenSearchDashboards][http] http server running at https://0.0.0.0:5601
server    log   [10:17:00.777] [error][monitoring][plugins][wazuh] getaddrinfo ENOTFOUND wazuh.manager
server    log   [10:17:06.430] [info][monitoring][plugins][wazuh] wazuh-monitoring-2023.48w index created
server    log   [10:17:06.441] [info][monitoring][plugins][wazuh] Settings added to wazuh-monitoring-2023.48w index
server    log   [10:17:06.751] [info][monitoring][plugins][wazuh] Bulk data to index wazuh-monitoring-2023.48w for 7 agents completed
server    log   [10:17:06.753] [error][monitoring][plugins][wazuh] Invalid URL
```

### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| The logs.level setting should not appear in the App settings application | :black_circle: | :black_circle: | :black_circle: |
| The App logs application should not appear in the side bar menu | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: The logs.level setting should not appear in the App settings application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: The App logs application should not appear in the side bar menu</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

## Backend

| Test | Result |
| --- |  --- |
| The default wazuh.yml should not contain the logs.level setting | :black_circle: |
| Logs of monitoring task should use the platform logging | :black_circle: |
| Logs of statistics task should use the platform logging | :black_circle: |
| Logs of initialize task should use the platform logging | :black_circle: |
| Logs of queue task should use the platform logging | :black_circle: |
| Logs of migration task should use the platform logging | :black_circle: |
| Logs of check updates plugin should use the platform logging | :black_circle: |
| Logs of core plugin should use the platform logging | :black_circle: |

**Details**
<details>
<summary>:black_circle: The default wazuh.yml should not contain the logs.level setting</summary>

</details>

<details>
<summary>:black_circle: Logs of monitoring task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of statistics task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of initialize task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of queue task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of migration task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of check updates plugin should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of core plugin should use the platform logging</summary>

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| The logs.level setting should not appear in the App settings application | :black_circle: | :black_circle: | :black_circle: |
| The App logs application should not appear in the side bar menu | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: The logs.level setting should not appear in the App settings application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: The App logs application should not appear in the side bar menu</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

## Backend

| Test | Result |
| --- |  --- |
| The default wazuh.yml should not contain the logs.level setting | :black_circle: |
| Logs of monitoring task should use the platform logging | :black_circle: |
| Logs of statistics task should use the platform logging | :black_circle: |
| Logs of initialize task should use the platform logging | :black_circle: |
| Logs of queue task should use the platform logging | :black_circle: |
| Logs of migration task should use the platform logging | :black_circle: |
| Logs of check updates plugin should use the platform logging | :black_circle: |
| Logs of core plugin should use the platform logging | :black_circle: |

**Details**
<details>
<summary>:black_circle: The default wazuh.yml should not contain the logs.level setting</summary>

</details>

<details>
<summary>:black_circle: Logs of monitoring task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of statistics task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of initialize task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of queue task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of migration task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of check updates plugin should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of core plugin should use the platform logging</summary>

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Comment by yenienserrano** [comment]
### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| The logs.level setting should not appear in the App settings application | :black_circle: | :black_circle: | :black_circle: |
| The App logs application should not appear in the side bar menu | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: The logs.level setting should not appear in the App settings application</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: The App logs application should not appear in the side bar menu</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

## Backend

| Test | Result |
| --- |  --- |
| The default wazuh.yml should not contain the logs.level setting | :black_circle: |
| Logs of monitoring task should use the platform logging | :black_circle: |
| Logs of statistics task should use the platform logging | :black_circle: |
| Logs of initialize task should use the platform logging | :black_circle: |
| Logs of queue task should use the platform logging | :black_circle: |
| Logs of migration task should use the platform logging | :black_circle: |
| Logs of check updates plugin should use the platform logging | :black_circle: |
| Logs of core plugin should use the platform logging | :black_circle: |

**Details**
<details>
<summary>:black_circle: The default wazuh.yml should not contain the logs.level setting</summary>

</details>

<details>
<summary>:black_circle: Logs of monitoring task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of statistics task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of initialize task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of queue task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of migration task should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of check updates plugin should use the platform logging</summary>

</details>

<details>
<summary>:black_circle: Logs of core plugin should use the platform logging</summary>

**Review by yenienserrano — APPROVED** [review]
LGTM

**Pull request merged**
