### PR TITLE
Add macOS log collector tab

### LINKED ISSUE #6389: Wazuh web interface to display agent "log collector" configuration details, skips the use of the "macos" logformat
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.x | Wazuh web interface | na | na | na |

When using the Wazuh web interface to directly peruse the "Log Collection" section of the configuration of a Wazuh agent running MacOS, only tabs for "Commands" and "Sockets" are included.  The "Logs" tab is completely missing, leaving the "macos" logformat log collection unaccounted for.  However, when I do an "Export PDF" with the "Log Collection" category selected for the MacOS agent, the "macos" logformat log collection does get accounted for in the PDF report.  

Please fill in this gap in the web interface.

Thanks,
Kevin Branch

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
This PR adds macOS log collector tab.
 
### Issues Resolved
Closes #6389 

### Evidence
image

### Test
- Install a macOS agent
- Configured log collector - [Documentation](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/configuration.html#collecting-macos-uls-logs-with-the-wazuh-agent)
- Go to Endpoints Summary
- Select the macOS agent
- Go to Configuration / Log collection
- Check the macOS tabs exists and the configuration is correct
image

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# Test

image
image

**Review by Desvelao — APPROVED** [review]
LGTM!

**Comment by JuanGarriuz** [comment]
### Test

#### Evidence

image

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!!

**Pull request merged**
