### PR TITLE
Allow upgrade agent from actions column

### PR DESCRIPTION
**Pull request by lucianogorza**
### Description
This PR's main objective is to provide Wazuh Dashboard users with the ability to easily update an outdated agent.
To achieve this, the `Upgrade button` has been added to the actions column of the agent's table.
Additionally, a `badge` has been included in the Version column to indicate if the agent is not up-to-date.
Finally, if there is any ongoing update, an `alert` is displayed showing the quantity in progress and the number of failures in the last 60 minutes, with the option to access the details of the failures.
 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6253

### Evidence
image
image
image
image
image
image

Command to create outdated agent with docker:
```
docker run --name os-dev-2120-agent-$(date +%s) --network os-dev-2.12.0 --label com.docker.compose.project=os-dev-2120 --env WAZUH_AGENT_VERSION=4.6.0 -d ubuntu:20.04 bash -c '
  apt update -y
  apt install -y curl lsb-release
  curl -so \wazuh-agent-${WAZUH_AGENT_VERSION}.deb \
    https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_${WAZUH_AGENT_VERSION}-1_amd64.deb \
    && WAZUH_MANAGER='wazuh.manager' WAZUH_AGENT_GROUP='default' dpkg -i ./wazuh-agent-${WAZUH_AGENT_VERSION}.deb

  /etc/init.d/wazuh-agent start
  tail -f /var/ossec/logs/ossec.log
'
```

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

### General

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Version column: up to date agent must show only the version | :black_circle: | :black_circle: | :black_circle: |
| Version column: outdated agent must show version and a badge | :black_circle: | :black_circle: | :black_circle: |
| Up to date agent: In actions column click more actions. Upgrade action must be disabled | :black_circle: | :black_circle: | :black_circle: |
| Outdated online agent: In actions column click more actions. Upgrade action must be enabled | :black_circle: | :black_circle: | :black_circle: |
| Outdated offline agent: In actions column click more actions. Upgrade action must be disabled | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Version column: up to date agent must show only the version</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Version column: outdated agent must show version and a badge</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Up to date agent: In actions column click more actions. Upgrade action must be disabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Outdated online agent: In actions column click more actions. Upgrade action must be enabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Outdated offline agent: In actions column click more actions. Upgrade action must be disabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Upgrade agents

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to an online and outdated agent, and click the upgrade action. Check the progress alert (API requests must be triggered every 3 seconds) and wait until the upgrade is finished (API requests must be stopped) | :black_circle: | :black_circle: | :black_circle: |
| Go to an online and outdated agent, and click the upgrade action. Refresh the entire page. The progress alert must be shown | :black_circle: | :black_circle: | :black_circle: |
| Go to an online and outdated agent, stop the Docker container, and click the upgrade action. Check the failed alert and open the modal to see the error details | :black_circle: | :black_circle: | :black_circle: |
| On the upgrade tasks modal, check different filters | :black_circle: | :black_circle: | :black_circle: |

**Details**

<details>
<summary>:black_circle: Go to an online and outdated agent, and click the upgrade action. Check the progress alert (API requests must be triggered every 3 seconds) and wait until the upgrade is finished (API requests must be stopped)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle:  Go to an online and outdated agent, and click the upgrade action. Refresh the entire page. The progress alert must be shown</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to an online and outdated agent, stop the Docker container, and click the upgrade action. Check the failed alert and open the modal to see the error details</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: On the upgrade tasks modal, check different filters</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by yenienserrano** [comment]
Maybe we could look for another alternative to show when an agent is out of date, for example a dot as in status and a tooltip, so that it stays in the same line.

**Comment by yenienserrano** [comment]
### General

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Version column: up to date agent must show only the version | :black_circle: | :black_circle: | :black_circle: |
| Version column: outdated agent must show version and a badge | :black_circle: | :black_circle: | :black_circle: |
| Up to date agent: In actions column click more actions. Upgrade action must be disabled | :black_circle: | :black_circle: | :black_circle: |
| Outdated online agent: In actions column click more actions. Upgrade action must be enabled | :black_circle: | :black_circle: | :black_circle: |
| Outdated offline agent: In actions column click more actions. Upgrade action must be disabled | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Version column: up to date agent must show only the version</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Version column: outdated agent must show version and a badge</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Up to date agent: In actions column click more actions. Upgrade action must be disabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Outdated online agent: In actions column click more actions. Upgrade action must be enabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Outdated offline agent: In actions column click more actions. Upgrade action must be disabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Upgrade agents

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to an online and outdated agent, and click the upgrade action. Check the progress alert (API requests must be triggered every 3 seconds) and wait until the upgrade is finished (API requests must be stopped) | :black_circle: | :black_circle: | :black_circle: |
| Go to an online and outdated agent, and click the upgrade action. Refresh the entire page. The progress alert must be shown | :black_circle: | :black_circle: | :black_circle: |
| Go to an online and outdated agent, stop the Docker container, and click the upgrade action. Check the failed alert and open the modal to see the error details | :black_circle: | :black_circle: | :black_circle: |
| On the upgrade tasks modal, check different filters | :black_circle: | :black_circle: | :black_circle: |

**Details**

<details>
<summary>:black_circle: Go to an online and outdated agent, and click the upgrade action. Check the progress alert (API requests must be triggered every 3 seconds) and wait until the upgrade is finished (API requests must be stopped)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle:  Go to an online and outdated agent, and click the upgrade action. Refresh the entire page. The progress alert must be shown</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to an online and outdated agent, stop the Docker container, and click the upgrade action. Check the failed alert and open the modal to see the error details</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: On the upgrade tasks modal, check different filters</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by yenienserrano** [comment]
It is making several requests to check which ones are in progress, ready and failed, and when you open the modal to see the tasks, the requests multiply.

**Comment by asteriscos** [comment]
### General

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Version column: up to date agent must show only the version | :green_circle: | :black_circle: | :black_circle: |
| Version column: outdated agent must show version and a badge | :green_circle: | :black_circle: | :black_circle: |
| Up to date agent: In actions column click more actions. Upgrade action must be disabled | :green_circle: | :black_circle: | :black_circle: |
| Outdated online agent: In actions column click more actions. Upgrade action must be enabled | :green_circle: | :black_circle: | :black_circle: |
| Outdated offline agent: In actions column click more actions. Upgrade action must be disabled | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Version column: up to date agent must show only the version</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Version column: outdated agent must show version and a badge</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Up to date agent: In actions column click more actions. Upgrade action must be disabled</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Outdated online agent: In actions column click more actions. Upgrade action must be enabled</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Outdated offline agent: In actions column click more actions. Upgrade action must be disabled</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

### Upgrade agents

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to an online and outdated agent, and click the upgrade action. Check the progress alert (API requests must be triggered every 3 seconds) and wait until the upgrade is finished (API requests must be stopped) | :green_circle: | :black_circle: | :black_circle: |
| Go to an online and outdated agent, and click the upgrade action. Refresh the entire page. The progress alert must be shown | :green_circle: | :black_circle: | :black_circle: |
| Go to an online and outdated agent, stop the Docker container, and click the upgrade action. Check the failed alert and open the modal to see the error details | :green_circle: | :black_circle: | :black_circle: |
| On the upgrade tasks modal, check different filters | :green_circle: | :black_circle: | :black_circle: |

**Details**

<details>
<summary>:green_circle: Go to an online and outdated agent, and click the upgrade action. Check the progress alert (API requests must be triggered every 3 seconds) and wait until the upgrade is finished (API requests must be stopped)</summary>

Chrome - :green_circle:

Peek 2024-03-11 19-40


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle:  Go to an online and outdated agent, and click the upgrade action. Refresh the entire page. The progress alert must be shown</summary>

Chrome - :green_circle:

Peek 2024-03-11 19-40

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Go to an online and outdated agent, stop the Docker container, and click the upgrade action. Check the failed alert and open the modal to see the error details</summary>

Chrome - :green_circle:


https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/85b85a6e-ef98-4756-b31d-5f1bad7e3f3f



Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: On the upgrade tasks modal, check different filters</summary>

Chrome - :green_circle:

Peek 2024-03-11 19-27


Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
