### PR TITLE
Removed agent RBAC filters from dashboard queries

### LINKED ISSUE #6943: Remove agent RBAC filters from dashboard queries
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.2 | - | Chrome, Firefox, Safari, etc |

**Description**
Currently, we apply filters only to get alerts from agents over whom the user has permission. When a query has too many clauses (1 for each agent ID), Wazuh indexer throws an exception because it cannot handle too many clauses. Therefore we need to remove these custom RBAC filters from the queries so that agent filtering can be achieved with the indexer policies.

**Preconditions**
Example of a use case that applies the agent filters:
https://documentation.wazuh.com/4.7/user-manual/user-administration/rbac.html#use-case-give-a-user-permissions-to-read-and-manage-a-group-of-agents

Related code:

https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.8.2-2.10.0/plugins/main/public/react-services/filter-authorization-agents.ts

https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.8.2-2.10.0/plugins/main/public/components/common/hooks/useAllowedAgents.ts

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description

Remove all use of RBAC filters such as `agents allowed`.

Closes #6943 

### Before

Screenshot 2024-08-26 at 11 51 05

### After

Screenshot 2024-08-26 at 11 52 53

## Remove allowed agents state from redux appStateReducers 

> [!NOTE]
> This method is placed on WzAuthorization and is used on every login.
> This adds the allowed agent's list on the app state

### Before

Screenshot 2024-08-26 at 12 28 01

https://github.com/user-attachments/assets/cdbaea8a-9528-4352-8cd2-e59eb3a18d38

### After

Screenshot 2024-08-26 at 12 33 33

## Remove allowed agents filters on reporting (wz-reporting)

>[!NOTE]
> extendedInformation

### Before

Screenshot 2024-08-26 at 15 58 21

### After 

Screenshot 2024-08-26 at 15 51 03

> [!NOTE]
> Test all module reports

https://github.com/user-attachments/assets/b8794541-2b6c-44b9-a42d-cae4f324ac9c

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by JuanGarriuz — APPROVED** [review]
### Test 


https://github.com/user-attachments/assets/a36df785-5d9f-41fd-9c5e-ab3c0bbcdac0

LGTM!!

**Review by jbiset — COMMENTED** [review]
## CR: :yellow_circle: 
_There are quite a few changes in the CHANGELOG that are not known to be correct because nothing is mentioned in the PR about them.
The change in this PR is not visible in the CHANGELOG_ 

## Test UI: :green_circle: 

### Remove allowed agents filters on data source :green_circle: 

image

### Remove allowed agents state from redux appStateReducers :green_circle: 

image

### Remove allowed agents filters on reporting (wz-reporting) :green_circle: 

[evidence_report.webm](https://github.com/user-attachments/assets/0908b978-cf5e-476e-92e0-9bc1c8153ad2)

**Review by jbiset — APPROVED** [review]
LGTM!

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Pull request merged**
