### PR TITLE
Add ability to disable the edition of configuration through API endpoints and UI

### LINKED ISSUE #6557: Disable settings with wazuh.yml configuration
# Description

We need to implement a new setting in the `wazuh.yml` configuration file that disables the access to modify Wazuh Dashboard settings.

## Tasks

- [x] Add new setting to wazuh.yml
- [x] Protect API endpoints related to updating the configuration
- [x] Hide the App settings -> Configuration tab (Only the Miscellaneous tab should be visible)
- [x] Hide the Remember server address in the Deploy new agent guide
- [x] Update documentation https://github.com/wazuh/wazuh-documentation/pull/7220
  - [x] Add the new setting

## Screenshots

Configuration tab
image
image

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request add the ability to enable or disable the edition of configuration through API endpoints and UI.

# Changes
- Add new setting `configuration.ui_api_editable` to manage if the configuration settings can be edited from API endpoints and UI.
  - Disable API endpoints related to update the configuration
  - Hide `Configuration`
  - Hide `Remember server address` button on deploy new agent guide
  - Hide `Settings` button on Statistics app
- Add API controllers decorator related to update the settings and protect the related routes
- Create `compose` utility to compose decorators of API endpoints
- Change the sign of routeDecoratorProtectedAdministrator
- Add tests related to the API endpoint controllers decorators
- Remove repeated message when there is an error updating the configuration from `App Settings`
- Refactor `Settings` components
  - Remove unused code
  - Minor enhancements
- Remove `pluginAppName` prop of `About` component. This is managed by the component now.
- Fix race condition of current app ID and the render of views
 
### Issues Resolved
#6557

### Evidence
image
image
image

### Test
# ability-configuration-editable

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should be visible. Update the configuration should work. | :black_circle: | :black_circle: | :black_circle: |
| With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should not be visible. | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should be visible. Update the configuration should work.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should not be visible.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test
# ability-configuration-editable

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should be visible. Update the configuration should work. | :green_circle: | :green_circle: | :black_circle: |
| With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should not be visible. | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should be visible. Update the configuration should work.</summary>

Chrome - :green_circle:

image

Firefox - :green_circle:

image

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should not be visible.</summary>

Chrome - :green_circle:

image

Firefox - :green_circle:

image

Safari - :black_circle:

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Comment by lucianogorza** [comment]
## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should be visible. Update the configuration should work. | 🟢 | :black_circle: | :black_circle: |
| With configuration.ui_api_editable setting disabled, go to App Settings and the Configuration tab should not be visible. | 🟢 | :black_circle: | :black_circle: |

**Details**
<details>
<summary>🟢 With configuration.ui_api_editable setting enabled, go to App Settings and the Configuration tab should be visible. Update the configuration should work.</summary>

Chrome - 🟢

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>🟢 With configuration.ui_api_editable setting disabled, go to App Settings and the Configuration tab should not be visible.</summary>

Chrome - 🟢

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by lucianogorza — APPROVED** [review]
LGTM!

**Review by JuanGarriuz — APPROVED** [review]

**Pull request merged**
