### PR TITLE
Change the value to display in the Top 5 agents table in Vulnerabilities Detection dashboard

### LINKED ISSUE #6419: Use agent.name in vulnerability dashboard table
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 03 | - |

**Description**
The vulnerabilities dashboard "Top 5 agents" table is currently showing the **_agent.id_** and makes it difficult to identify which agent we are talking about. We should change the field and table label to display the `agent.name` so it's easier to identify.

**Expected Result**
1. The vulnerabilities dashboard "Top 5 agents" table should render the `agent.name` field _(instead of the agent.id)_

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request replaces the value to display in the Top 5 agents table of Vulnerabilities Detection > Dashboard.
 
### Issues Resolved
#6419

### Evidence
image

### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With data, go to Vulnerabilities Detection > Dashboard, and the Top 5 agents must display the agent name | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: With data, go to Vulnerabilities Detection > Dashboard, and the Top 5 agents must display the agent name</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by yenienserrano — APPROVED** [review]
CR: ✅ 
Test: ✅ 

image

**Comment by JuanGarriuz** [comment]
### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With data, go to Vulnerabilities Detection > Dashboard, and the Top 5 agents must display the agent name | 🟢 | :black_circle: | :black_circle: |

**Details**
<details>
<summary> 🟢  With data, go to Vulnerabilities Detection > Dashboard, and the Top 5 agents must display the agent name</summary>

Chrome - 🟢 
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 
image

**Pull request merged**
