### PR TITLE
Change register agent styles

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description
Change the styles of the agent view so it does not look like a modal
 
### Issues Resolved
- #7071

### Evidence

screencapture-localhost-5601-app-endpoints-summary-2024-11-14-13_44_32

### Test

Navigate to register agent view and check changes

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by chantal-kelm — DISMISSED** [review]
CR: ✅ 
TEST: ✅ 

Captura de pantalla 2024-11-13 a la(s) 4 31 35 p  m
Captura de pantalla 2024-11-13 a la(s) 4 32 26 p  m
Captura de pantalla 2024-11-13 a la(s) 4 32 42 p  m
Captura de pantalla 2024-11-13 a la(s) 4 32 37 p  m

**Comment by JuanGarriuz** [comment]
### CR 🟢 

### Test 🟢 

image
image
image
image
image
image

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!!

**Comment by Desvelao** [comment]
**suggestion**: I think we should remove the rendered back button. The browser back button should do the work. Moreover, the rendered back button in the UI is redirecting to the overview of agents instead and taking into account the view is accessible from URL, in some cases, clicking in the back button will redirect to another view.

**Comment by asteriscos** [comment]
It make sense to remove de back button, because this view can be accessed from the home view for example. Therefore back button can be confusing. If we remove it the user can use the breadcrumb to navigate.

image

**Review by asteriscos — CHANGES_REQUESTED** [review]
It makes sense to remove the back button, because this view can be accessed from the home view for example. Therefore the back button can be confusing. If we remove it the user can use the breadcrumb to navigate.

image

**Comment by yenienserrano** [comment]
Back button removed in [abd86f2](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7149/commits/abd86f2afff67adff732946e031a53a4748d3c4d)

screencapture-localhost-5601-app-endpoints-summary-2024-11-14-13_44_32

**Review by asteriscos — APPROVED** [review]
CR: :green_circle: 
Test: :green_circle: 

Chrome :green_circle: 

localhost_5601_app_endpoints-summary

Firefox :green_circle: 

FireShot Capture 017 - Wazuh - localhost

**Review by Machi3mfl — APPROVED** [review]
CR: ✅ 
Test: ✅ 

## Safari

https://github.com/user-attachments/assets/2b4c4ec5-22ab-4876-9727-e0b3ad907e88

## Chrome

https://github.com/user-attachments/assets/b88f173e-436f-4c30-be20-4ac4474ee1e4

**Pull request merged**
