### PR TITLE
Fixed behavior in Configuration Assessment when changing API

### PR DESCRIPTION
**Pull request by jbiset**
## Description
This PR fixes rendering when changing the API in Configuration Assessment when you have an agent pinned.
 
## Issues Resolved
- #6763 

## Evidence

[evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/aa08f375-d8ad-4572-a39f-6fd13362cbab)

## Test

- Navigate to Configuration Assessment.
- Pin an agent.
- Go to Home -> Overview
- Go to Configuration Assessment.
- Change the API.
- Check that the agent selection screen appears in Configuration Assessment.

## Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test 🟢 

<details><summary>Evidence</summary>

image
image
image
image


</details>

**Comment by JuanGarriuz** [comment]
### Test 🟢 

<details><summary>Evidence</summary>

image
image
image
image


</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Review by chantal-kelm — APPROVED** [review]
https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/2b4695e6-e7d4-4d95-9f7a-05f89aeb93db

**Pull request merged**
