### PR TITLE
Replace discover AWS

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description
This PR, replaces the events tab on the Amazon Web Services module
 
### Issues Resolved

- #6279 

### Evidence

image

# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |

- Apply filters using search bar input

<details>

</details>

- Apply filters using the search bar `add filter` feature

<details>

</details>

- Apply filters using the date picker

<details>

</details>

- Apply filters with no results (Check the `No results match your search criteria` message)

<details>

</details>

- Use the `saved queries` feature (Check saved queries CRUD)

<details>

</details>

## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |

- Check histogram chart hits consistency 

<details>

</details>

- Use chart options (three points: maximize, minimize, inspect) 

<details>

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |

- Check all table header features (sort, show/hide columns, density, etc)

<details>

</details>

- Check table pagination and rows per page

<details>

</details>

- Check document detail flyout

<details>

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Machi3mfl** [comment]
# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |

- Apply filters using search bar input

<details>


</details>

- Apply filters using the search bar `add filter` feature

<details>


</details>

- Apply filters using the date picker

<details>


</details>

- Apply filters with no results (Check the `No results match your search criteria` message)

<details>


</details>

- Use the `saved queries` feature (Check saved queries CRUD)

<details>


</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :black_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: | :black_circle: | :black_circle: |

- Check histogram chart hits consistency 

<details>


</details>


- Use chart options (three points: maximize, minimize, inspect) 

<details>


</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :black_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :black_circle: | :black_circle: | :black_circle: |

- Check all table header features (sort, show/hide columns, density, etc)

<details>


</details>


- Check table pagination and rows per page

<details>


</details>

- Check document detail flyout

<details>


</details>

**Review by Machi3mfl — CHANGES_REQUESTED** [review]
# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :green_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :green_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :green_circle: | :black_circle: | :black_circle: |

- Apply filters using search bar input

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/268e677e-3807-4cc0-81c1-6a5af63fa4c8

</details>

- Apply filters using the search bar `add filter` feature

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/7697c16a-affa-4792-b971-4022275d2352

</details>

- Apply filters using the date picker

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/a5869014-150b-45ab-8f04-2959860e5ba0

</details>

- Apply filters with no results (Check the `No results match your search criteria` message)

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/c6d163a3-3bcf-4a10-9063-c34307875398

</details>

- Use the `saved queries` feature (Check saved queries CRUD)

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/3f7179a0-b890-4ad5-9ff3-4d4a3ac3edc5

</details>


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency | :green_circle: | :black_circle: | :black_circle: |
| Use chart options (three points: maximize, minimize, inspect) | :green_circle: | :black_circle: | :black_circle: |

- Check histogram chart hits consistency 

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/9ecbcded-8a63-4298-90de-04970e00d0e0

</details>


- Use chart options (three points: maximize, minimize, inspect) 

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/8810a079-6ffb-4203-951b-84d97b00197f

</details>

## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) | :green_circle: | :black_circle: | :black_circle: |
| Check table pagination and rows per page | :green_circle: | :black_circle: | :black_circle: |
| Check document detail flyout | :green_circle: | :black_circle: | :black_circle: |

- Check all table header features (sort, show/hide columns, density, etc)

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/bc99fa45-0a7d-4adf-bfa7-1d07b1f682e3

</details>


- Check table pagination and rows per page

<details>

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/60b266af-fa34-44f6-8521-339e8400434f

</details>

- Check document detail flyout

<details>

Screenshot 2024-02-15 at 11 47 28


</details>

**Comment by yenienserrano** [comment]
Looking at the bug commented out in the test, I have seen some problems in the flyout. For example, when the field has a very long name, it pushes the value column, leaving it with little space, it was also missing the styles to the table.

## Possible solutions

1. 
image


2. 
image

**Comment by Machi3mfl** [comment]
> Looking at the bug commented out in the test, I have seen some problems in the flyout. For example, when the field has a very long name, it pushes the value column, leaving it with little space, it was also missing the styles to the table.
> 
> ## Possible solutions
> 
> image
> 
> 
> image

nice, @yenienserrano. Good job 

Screenshot 2024-02-15 at 11 47 28

**Review by Machi3mfl — APPROVED** [review]
CR ✅ 
Testing ✅

**Comment by Tostti** [comment]
# Tests

## Search bar

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Apply filters using search bar input | :black_circle: | :green_circle: | :black_circle: | 
| Apply filters using the search bar `add filter` feature | :black_circle: | :green_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker |:black_circle: | :green_circle: | :black_circle: | 
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: |:green_circle: | :black_circle: | 
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :green_circle: | :black_circle: |


## Histogram chart

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check histogram chart hits consistency |:black_circle: | :green_circle: | :black_circle: | 
| Use chart options (three points: maximize, minimize, inspect) | :black_circle: |:green_circle: | :black_circle: | 
- Check histogram chart hits consistency 


## Data grid

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check all table header features (sort, show/hide columns, density, etc) |  :black_circle: | :green_circle: | :black_circle: |
| Check table pagination and rows per page | :black_circle: |:green_circle: | :black_circle: | 
| Check document detail flyout | :black_circle: | :green_circle: | :black_circle: | 


https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/d3476a3c-ed2f-47ce-b4d9-c7c966258dab

**Review by Tostti — APPROVED** [review]
Test ✅ 
CR ✅ 

LGTM

**Pull request merged**
