### PR TITLE
Add setting to disable update check service in dashboard

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
This pull request adds setting to disable update check service in dashboard. The new settings is `wazuh.updates.disabled` which by default is set to `false`, therefore the app will always try to check for available updates unless it's explicitly set to true.
 
### Issues Resolved
Closes https://github.com/wazuh/wazuh-dashboard/issues/158

### Evidence

`wazuh.updates.disabled: false`

image

`wazuh.updates.disabled: true`

image

### Test
Check there are no check updates features in the app:
- The initial requests to check for the user configuration and cached updated should not ve made when the setting is true
  - `/api/wazuh-check-updates/user-preferences/me`
  - `/api/wazuh-check-updates/updates`
- In the **_Server APIs_** table, these elements must not be rendered:
  - The **_Version_** and the **_Update status_** columns
  - The **_Check updates_** button on top of the table
  - The **_Disable updates notifications_** check on top of the table

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by jbiset** [comment]
## Error when clicking Check connection action on table row

image

**Comment by asteriscos** [comment]
> ## Error when clicking Check connection action on table row
> image

Fixed!

**Review by jbiset — APPROVED** [review]
## CR: :green_circle: 

## Test UI: :green_circle: 

### `wazuh.updates.disabled: false` :green_circle: 

image

### `wazuh.updates.disabled: true` :green_circle: 

image

In the Server APIs table, these elements must not be rendered:

- [x] The Version and the Update status columns
- [x] The Check updates button on top of the table
- [x] The Disable updates notifications check on top of the table

**Review by yenienserrano — APPROVED** [review]
CR: ✅ 
Test: ✅ 

<details><summary>Details</summary>


image

</details>

**Pull request merged**
