### PR TITLE
Remove groups.js angular controller

### PR DESCRIPTION
**Pull request by lucianogorza**
### Description
This pull request removes the AngularJS controller for manage groups.
 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6540

### Evidence
[groups.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/ee7e9fa3-4df6-40d3-ab69-61e4f6cde03b)

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Create and delete groups | :black_circle: | :black_circle: | :black_circle: |
| Check group detail page | :black_circle: | :black_circle: | :black_circle: |
| Go to group detail -> Manage agents: Add and remove agents | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Create and delete groups</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Check group detail page</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to group detail -> Manage agents: Add and remove agents</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# Test

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Create and delete groups | :green_circle: | :black_circle: | :black_circle: |
| Check group detail page | :green_circle: | :black_circle: | :black_circle: |
| Go to group detail -> Manage agents: Add and remove agents | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Create and delete groups</summary>

Chrome - :green_circle:
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Check group detail page</summary>

Chrome - :green_circle:
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Go to group detail -> Manage agents: Add and remove agents</summary>

Chrome - :green_circle:
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by Desvelao — APPROVED** [review]
LGTM!

**Comment by JuanGarriuz** [comment]
a

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

### CR ✔️ 

### Test ✔️ 

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Create and delete groups | 🟢 | :black_circle: | :black_circle: |
| Check group detail page | 🟢 | :black_circle: | :black_circle: |
| Go to group detail -> Manage agents: Add and remove agents | 🟢 | :black_circle: | :black_circle: |

**Details**
<details>
<summary>🟢 Create and delete groups</summary>

Chrome - 🟢

image
image
image
image
image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>🟢 Check group detail page</summary>

Chrome - 🟢

image
image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>🟢 Go to group detail -> Manage agents: Add and remove agents</summary>

Chrome - 🟢

image
image
image
image


Firefox - :black_circle:

Safari - :black_circle:

</details>

**Pull request merged**
