### PR TITLE
Fix vulnerability detector event filter

### PR DESCRIPTION
**Pull request by jbiset**
## Description
This issue fixes arbitrary behavior in the implicit filter disabling/enabling mechanism.
 
## Issues Resolved
- #6316 

## Evidence
[screen-capture.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/5bb20831-dec5-4111-8009-33faf8c89873)

## Test

- Check changing filters and changing their states on different screens (for example, MITER ATT&CK, Vulnerability Detection, FIM, etc.), as well as checking changing tabs on the same screen.
- Among the filter changes, test, pin them, negate them, delete them.
- Implicit filters must be kept implicit (they cannot be deleted and do not have a context menu when clicked).

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by lucianogorza** [comment]
## Test

### Vulnerability Detection
[screen-capture.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/7d91a284-6bde-44ca-b052-9a93913e9477)

**Review by lucianogorza — CHANGES_REQUESTED** [review]
It appears that there is a bug when multiple filters of the same field are applied.

**Comment by lucianogorza** [comment]
## Test 🟢 

### MITRE ATT&CK
[MITRE.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/f5481840-f747-47e0-9fad-6f5ec4161309)

### Vulnerability Detection
[Vulnerabilities.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/cfc1e601-3456-4579-9d67-71673f2b6a45)

**Review by lucianogorza — APPROVED** [review]
LGTM

**Review by Tostti — APPROVED** [review]
https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/0df28188-276a-46ad-8825-bc9074e70470

Test ✅ 
CR ✅ 

LGTM

**Pull request merged**
