### PR TITLE
Fix endpoints summary agent action buttons navigation

### LINKED ISSUE #6892: View agent details buttons don't work
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 02 | Chrome, Firefox, Safari, etc |

**Description**

In the endpoints summary table, the action buttons that involve navigation don't work properly.

**Preconditions**
1. Have agents

**Steps to reproduce**
1. Navigate to Endpoints summary
2. Click on a row `...` button
3. Click on `View agent details` button
4. Check it doesn't navigate

**Expected Result**
1. Should navigate

**Actual Result**
1. Doesn't

**Screenshots**

Peek 2024-08-01 12-03

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
Hi team,
this pull request fixes the navigation method of the endpoint summary table action buttons, so the buttons use an in-module navigation method.
 
### Issues Resolved
Closes #6892 

### Evidence
Peek 2024-08-01 11-51

### Test

1. Go to Endpoints summary
2. Click on the :eye: button of an agent row to navigate to the agent details. Then go back in the browser history.
3. Click on the `...` button of an agent row to expand the actions, then click on `View agent details` to test the navigation.
4. Click on the `...` button of an agent row to expand the actions, then click on `Agent configuration` to navigate to the agent configuration.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by chantal-kelm — APPROVED** [review]
https://github.com/user-attachments/assets/ece329df-88a4-4920-b12b-7c35e0552f3b

**Review by JuanGarriuz — APPROVED** [review]
### Test 🟢 

1. Go to Endpoints summary
2. Click on the :eye: button of an agent row to navigate to the agent details. Then go back in the browser history.
3. Click on the `...` button of an agent row to expand the actions, then click on `View agent details` to test the navigation.
4. Click on the `...` button of an agent row to expand the actions, then click on `Agent configuration` to navigate to the agent configuration.

https://github.com/user-attachments/assets/3e450c7a-7a10-4319-8261-31a892b58422

### CR 🟢 

LGTM!!!

**Review by yenienserrano — APPROVED** [review]
LGTM

Uploading Screen Recording 2024-08-01 at 12.29.31 PM.mov…

**Comment by Machi3mfl** [comment]
CR: ✅ 
Test: ✅ 

https://github.com/user-attachments/assets/f79ed5c8-9b69-442c-bc67-822fcf0b9578

**Pull request merged**
