### PR TITLE
Fix maximized visualizations styles

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description

Fixed the styles when maximising a visualisation as some were too big and others did not occupy the whole screen, the docked menu is taken into account.
 
### Issues Resolved
- #6859 

### Evidence

https://github.com/user-attachments/assets/ba4ef531-a2b7-464e-abb5-3c81e1bcd985

### Test

1. Navigate to the different dashboards and test maximising visualisations
2. Navigate to events and try maximising the displays
3. They should all be rendered accordingly and should take into account the docked menu or not.

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by jbiset — DISMISSED** [review]
## CR: :green_circle: 

## Test UI: :green_circle: 

### Evidence

[evidence.webm](https://github.com/user-attachments/assets/284f1299-3d42-41d0-a49c-5d102e3ffbc7)

**Comment by lucianogorza** [comment]
## CR 🟢 
## Test UI 🟡

### Desktop 🟢 

[desktop.webm](https://github.com/user-attachments/assets/6c4100fb-8d3c-43d3-aa86-51866b5de2c1)

### Mobile 🟡 

image

**Comment by lucianogorza** [comment]
### Mobile 🟢 

image
image

**Review by jbiset — COMMENTED** [review]
## Mobile

**THREAT HUNTING**

**With legend**

image

**Without legend**

image

MITRE

**With legend**

image

**Without legend**

image

**Review by jbiset — APPROVED** [review]

**Pull request merged**
