### PR TITLE
Remove total outdated agents statistic from Endpoint Summary

### PR DESCRIPTION
**Pull request by lucianogorza**
### Description

This PR addresses the following changes:

1. Removed outdated agents' statistic from the Endpoints Summary page:

    - The outdated agents' statistic has been removed to streamline the information displayed on the Endpoints Summary page.

2. Moved state management to table component:
    - The state management for the total number of outdated agents has been shifted from the Endpoints Summary page to the table component. This ensures that the table component independently manages and reflects the accurate count of outdated agents.
 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6736

### Evidence
image
image
image
image

### Test

> [!IMPORTANT]  
> Test with a real 4.9.0 manager and at least one outdated agent.

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verified that the Endpoints Summary page no longer displays the outdated agents' statistic. | :black_circle: | :black_circle: | :black_circle: |
| If there are outdated agents, then the agents table must display the total. | :black_circle: | :black_circle: | :black_circle: |
| If there are outdated agents, turning on the switch should make the table display only those agents. | :black_circle: | :black_circle: | :black_circle: |
| If there are no outdated agents, then the agents table should disable the switch. | :black_circle: | :black_circle: | :black_circle: |
| Verified that the Agent Welcome page (with data) adapts the components correctly por 850px screen width. | :black_circle: | :black_circle: | :black_circle: |
| Check Endpoint Summary statistic titles: Must be "Top 5 OS" and "Top 5 groups". | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Verified that the Endpoints Summary page no longer displays the outdated agents' statistic.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: If there are outdated agents, then the agents table must display the total.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: If there are outdated agents, turning on the switch should make the table display only those agents.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: If there are no outdated agents, then the agents table should disable the switch.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Verified that the Agent Welcome page (with data) adapts the components correctly por 850px screen width.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Check Endpoint Summary statistic titles: Must be "Top 5 OS" and "Top 5 groups".</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!!

**Review by asteriscos — CHANGES_REQUESTED** [review]
Test: :red_circle: 

The total amount of outdated agents doesn't consider the filters applied to the table, such as a particular group selected. 
To make the outdated agents value consistent with the table results, it should include all pre-applied filters to the query.

Peek 2024-06-04 18-04

**Comment by lucianogorza** [comment]
> Test: 🔴
> 
> The total amount of outdated agents doesn't consider the filters applied to the table, such as a particular group selected. To make the outdated agents value consistent with the table results, it should include all pre-applied filters to the query.
> 
> Peek 2024-06-04 18-04 [ Peek 2024-06-04 18-04 ](https://private-user-images.githubusercontent.com/9343732/336526502-76af62e2-ae41-4d11-9d74-a266d95add42.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjM2MDgsIm5iZiI6MTcxNzUyMzMwOCwicGF0aCI6Ii85MzQzNzMyLzMzNjUyNjUwMi03NmFmNjJlMi1hZTQxLTRkMTEtOWQ3NC1hMjY2ZDk1YWRkNDIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTc0ODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzI0ODBmYWFlYWQ0ZTA5N2YwODlkZTk4ZThlYjc2OGNjNjdhYjAwOTJhZWRlOWQxY2M4ZjRmYTE3MTExNzQwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rwkuOzky8vlzZp5b0dGjxYvrRNUWvmT_MFerfQDBg7U) [ ](https://private-user-images.githubusercontent.com/9343732/336526502-76af62e2-ae41-4d11-9d74-a266d95add42.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjM2MDgsIm5iZiI6MTcxNzUyMzMwOCwicGF0aCI6Ii85MzQzNzMyLzMzNjUyNjUwMi03NmFmNjJlMi1hZTQxLTRkMTEtOWQ3NC1hMjY2ZDk1YWRkNDIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTc0ODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzI0ODBmYWFlYWQ0ZTA5N2YwODlkZTk4ZThlYjc2OGNjNjdhYjAwOTJhZWRlOWQxY2M4ZjRmYTE3MTExNzQwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rwkuOzky8vlzZp5b0dGjxYvrRNUWvmT_MFerfQDBg7U)

Fixed in this [commit ](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6737/commits/6b5b899d1acc24de330bff9d549c5b6d9f8a2e4b)

**Comment by asteriscos** [comment]
| Test | Firefox | 
| --- |  --- | 
| Verified that the Endpoints Summary page no longer displays the outdated agents' statistic. | :green_circle: | 
| If there are outdated agents, then the agents table must display the total. | :green_circle: | 
| If there are outdated agents, turning on the switch should make the table display only those agents. | :green_circle: | 
| If there are no outdated agents, then the agents table should disable the switch. | :green_circle: | 
| Verified that the Agent Welcome page (with data) adapts the components correctly por 850px screen width. | :green_circle: | 
| Check Endpoint Summary statistic titles: Must be "Top 5 OS" and "Top 5 groups". | :green_circle: | 

**Details**
<details>
<summary>:green_circle: Verified that the Endpoints Summary page no longer displays the outdated agents' statistics.</summary>


Firefox - :green_circle:

image



</details>

<details>
<summary>:green_circle: If there are outdated agents, then the agent's table must display the total.</summary>


Firefox - :green_circle:

image


</details>

<details>
<summary>:green_circle: If there are outdated agents, turning on the switch should make the table display only those agents.</summary>


Firefox - :green_circle:

image



</details>

<details>
<summary>:green_circle: If there are no outdated agents, then the agents table should disable the switch.</summary>


Firefox - :green_circle:

image


</details>

<details>
<summary>:green_circle: Verified that the Agent Welcome page (with data) adapts the components correctly por 850px screen width.</summary>


Firefox - :green_circle:

image


</details>

<details>
<summary>:green_circle: Check Endpoint Summary statistic titles: Must be "Top 5 OS" and "Top 5 groups".</summary>


Firefox - :green_circle:

image


</details>

**Review by asteriscos — APPROVED** [review]
CR: :green_circle: 
Test: :green_circle:

**Pull request merged**
