### PR TITLE
Implement embeddable dashboard on PCI DSS

### LINKED ISSUE #6502: [Remove discover] Implement embeddable dashboard on PCI DSS module
## Description

We have to implement the embeddable dashboard on PCI DSS -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Implement the embeddable dashboard on PCI DSS -> dashboard tab
  - [x] Implement the usage of DataSoruce
- [x] Refactor the `Controls` tab to use Data Source
  - [x] Main view
  - [x] Flyout
    - [x] Replace table by WzDiscover and DataSource

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request replaces the `Dashboard` tab and adapts the `Panels` tab on PCI DSS application
 
### Issues Resolved
#6502

### Evidence
image
image
image
image

### Test

Go to PCI DSS > Dashboard:

Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.
The visualizations have to be updated according to the filters applied in the searchbar.
The visualizations have to be updated when a search is performed in the searchbar.
If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
If there is SampleData, the corresponding SampleData message must appear.
If an agent is pinned, the views must be updated and changed to the agent view, if applicable.
Check filter behavior with respect to hide alerts, allow agents and filter order.

Go to PCI DSS > Controls
Check the requirements filters on the on the left side filters the requirements on the right side
Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.
In the details flyout click on the show on dashboard and events links, they should display this tabs with a filter related to the selected requirement
The link on the flyout table should redirect to Endpoint Summary and Rules respectively

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test 🔴 


https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/6e166390-8af2-48ac-b78a-1257d19ed163

**Comment by lucianogorza** [comment]
## Test

Go to PCI DSS > Dashboard:

- [ ] Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.

<details><summary>Details</summary>

</details>

- [ ] The visualizations have to be updated according to the filters applied in the searchbar.

<details><summary>Details</summary>

</details>

- [ ] The visualizations have to be updated when a search is performed in the searchbar.

<details><summary>Details</summary>

</details>

- [ ] If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.

<details><summary>Details</summary>

</details>

- [ ] If there is SampleData, the corresponding SampleData message must appear.

<details><summary>Details</summary>

</details>

- [ ] If an agent is pinned, the views must be updated and changed to the agent view, if applicable.

<details><summary>Details</summary>

</details>

- [ ] Check filter behavior with respect to hide alerts, allow agents and filter order.

Go to PCI DSS > Controls

- [ ] Check the requirements filters on the on the left side filters the requirements on the right side

<details><summary>Details</summary>

</details>

- [ ] Click on the requirement to open the flyout and interact with the search bar and links, they should work as expected. The search should take into account optionally the allowed agents and the hide manager alerts plugin setting if enabled.

<details><summary>Details</summary>

</details>

- [ ] In the details flyout click on the show on dashboard and events links, they should display this tabs with a filter related to the selected requirement

<details><summary>Details</summary>

</details>

- [ ] The link on the flyout table should redirect to Endpoint Summary and Rules respectively

<details><summary>Details</summary>

</details>

**Comment by Desvelao** [comment]
@lucianogorza , this toast appears due the old visualizations related to the PCI DSS were removed from the backend side and in the development branch, there logic related to the old dashboard. When we remove this logic, the toast should not appear.

Related image:
https://github.com/wazuh/wazuh-dashboard-plugins/pull/6504#issuecomment-2093272644

**Review by lucianogorza — CHANGES_REQUESTED** [review]
- When the user unpins the agent, the agent is not removed from the url.
- In `Controls `Tab, when the flyout is opened, the query is repeated

Details in comment https://github.com/wazuh/wazuh-dashboard-plugins/pull/6504#issuecomment-2093272644

**Review by JuanGarriuz — DISMISSED** [review]
LGTM!!!

**Pull request merged**
