### PR TITLE
Fix home view kpis styles

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description
Fixes styling and redirection problem in home page KPIs 
 
### Issues Resolved
- #6406 

### Evidence

Safari

image

Chrome

image

image

image

### Test

1. Check of the Home view KPIs must have the same font size and font-weight
2. check that the KPIs Active Agents and Disconnected Agents redirect to the endpoint summary with the selected filter in the table

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by lucianogorza — DISMISSED** [review]
## CR 🟢 
## Test 🟢 
image
image
image
image

**Comment by JuanGarriuz** [comment]
## Test

image
image
image

**Review by JuanGarriuz — DISMISSED** [review]
LGTM!!

**Review by Desvelao — APPROVED** [review]
LGTM!

image
image
image

**Pull request merged**
