### PR TITLE
The selected filter is not applied when redirecting to the events tab in the file integrity monitoring module

### LINKED ISSUE #6846: The selected filter is not applied when redirecting to the events tab in the file integrity monitoring module
## Description

When we enter the File integrity monitoring module in the inventory tab, we select a value from the table, the flyout is displayed and we click on the recent events icon to go to the events tab, the filter does not apply when redirecting.

https://github.com/user-attachments/assets/a068d2ba-ab36-4efc-add5-5abc9df509c6

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

This PR fix the issue the selected filter is not applied when redirecting to the events tab in the file integrity monitoring module.
 
### Issues Resolved

#6846 

### Evidence

https://github.com/user-attachments/assets/077ed502-5555-4193-8a98-7630377210e9

### Test

- Go to the File integrity monitoring module in the inventory tab, we select a value from the table, the flyout is displayed and we click on the recent events icon to go to the events tab, when redirecting to events the filter selected should be applied.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by yenienserrano** [comment]
Test: 🟡 

When navigating back to inventory, the flyout reopens again, is that expected?

https://github.com/user-attachments/assets/791c1b94-f7b8-4dc7-90cc-a5d36cf0b97e

**Review by yenienserrano — COMMENTED** [review]
The changelog is missing

**Comment by jbiset** [comment]
> Test: 🟡
> 
> When navigating back to inventory, the flyout reopens again, is that expected?
> 
>  Screen.Recording.2024-07-19.at.12.09.36.PM.mov

It was tested in 4.7.2 and 4.8.1 and the behavior is the same. Therefore, it is assumed that it is expected.

**Review by jbiset — COMMENTED** [review]
## CR: :green_circle: (Add the CHANGELOG)

## Test UI: :green_circle: 

### Evidence

[Evidence.webm](https://github.com/user-attachments/assets/8f540a9c-7727-49c8-bbd6-d130f2e5bcdd)

**Review by yenienserrano — APPROVED** [review]
LGTM

**Review by jbiset — DISMISSED** [review]
LGTM

**Review by jbiset — APPROVED** [review]
LGTM

**Review by yenienserrano — APPROVED** [review]

**Pull request merged**
