### PR TITLE
Fix refreshing index pattern fields does not include the scripted fields

### LINKED ISSUE #3632: Scripted fields disappear when the app refreshes the index pattern `fields`
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

**Description**
If the users create scripted fields, these are removed when accessing the app and it refreshes the `fields` of the index pattern.

To refresh the `fields` for the index pattern, it does a request to:
```GET /api/index_patterns/_fields_for_wildcard?pattern=${pattern}&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score```

The response includes:
  - the existent `fields` in the indices that match with the index pattern
  - meta fields: `_source`, `_id`, `_type`, `_index`, `score`
  
As the scripted fields are not present in the indices, the field is not returned in the response of the above request. These fields are used to update the index pattern in https://github.com/wazuh/wazuh-kibana-app/blob/v4.2.1-7.10.2/public/react-services/saved-objects.js#L271-L285

The method that updates the index patterns receive the `fields`:
https://github.com/wazuh/wazuh-kibana-app/blob/v4.2.1-7.10.2/public/react-services/saved-objects.js#L178-L200

**Steps to reproduce**
1. Go to `Stack Management > Index patterns > wazuh-alerts-*` and create a `Scripted field`
2. Force the app to refresh the index pattern. For example, force the health check (`/app/wazuh#/health-check`) or change the index pattern should refresh it.
3. Update the browser tab and review the scripted field is not defined in the index pattern

**Expected Result**
The scripted fields should not be removed when refreshing the index pattern by the app.

**Actual context**
The scripted fields are presents in the `fields` index pattern property like you can see in the screenshot: (the field is called `custom`).

image

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request fixes that refreshing the index pattern fields does not include the scripted fields.

Changes:
- Replaced custom service logic for a similar one to the Dashboards
  Management/Index pattern of the platform
  - Use a more low level logic to update the index pattern fields taking
      in account the scripted fields
  - The SavedObjects.refreshIndexPattern now throws an error when
      something fails instead of return the error message
- Removed the ability to define fields that are not fields from the
  indices that match the index pattern or scripted fields 
- Display a warning in the check fields or when refreshing the index
    pattern of the default configurated index pattern of the plugins

### Issues Resolved
#3632

### Evidence
image
image
image

### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensuring a scripted field is added to the index pattern, run or force the alerts pattern check is run. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |
| Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |
| Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. Index data with new fields for the index pattern (you can use some category of sample data), then go to Events tab and open an alert that contain a new field. Then use the Reload button of the toast. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, run or force the alerts pattern check is run. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. Index data with new fields for the index pattern (you can use some category of sample data), then go to Events tab and open an alert that contain a new field. Then use the Reload button of the toast. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensuring a scripted field is added to the index pattern, run or force the alerts pattern check is run. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |
| Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |
| Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. Index data with new fields for the index pattern (you can use some category of sample data), then go to Events tab and open an alert that contain a new field. Then use the Reload button of the toast. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, run or force the alerts pattern check is run. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

image
image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. Index data with new fields for the index pattern (you can use some category of sample data), then go to Events tab and open an alert that contain a new field. Then use the Reload button of the toast. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!

**Comment by yenienserrano** [comment]
### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensuring a scripted field is added to the index pattern, run or force the alerts pattern check is run. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |
| Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |
| Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. Index data with new fields for the index pattern (you can use some category of sample data), then go to Events tab and open an alert that contain a new field. Then use the Reload button of the toast. The scripted field should not be lost (use Discover or Events tab to check it is there) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, run or force the alerts pattern check is run. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensuring a scripted field is added to the index pattern, use the index pattern selector to select the index pattern with the scripted field. Index data with new fields for the index pattern (you can use some category of sample data), then go to Events tab and open an alert that contain a new field. Then use the Reload button of the toast. The scripted field should not be lost (use Discover or Events tab to check it is there)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by yenienserrano — APPROVED** [review]
LGTM

**Pull request merged**
