### PR TITLE
Fix statistics visualizations when cluster mode is disabled

### PR DESCRIPTION
**Pull request by lucianogorza**
### Description
This PR solves the followins issue in `Server Management -> Statistics`:
- Fix initial error when cluster mode is disabled.
- Replace the definitions of visualizations `Events processed` and `Events Dropped` according to the cluster mode, and this way only add the aggregation by the field `node.name` when cluster mode is enabled.
- Apply visualizations filter when node is selected.

 
### Issues Resolved
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6343

#### Cluster mode disabled
Cluster mode disabled

#### Cluster mode enabled
Cluster mode enabled

#### Cluster mode enabled and filtered by node
Filtered by node

### Test

1. Disabled cluster mode from the server configuration: https://documentation.wazuh.com/current/user-manual/configuring-cluster/index.html
2. Go to `Server Management -> Statistics`.
3. Check the visualizations from both tabs.
4. Enabling cluster mode and repeat steps 2 and 3.
5. Filter by node and check visualizations.

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by yenienserrano — DISMISSED** [review]
CR: ✅ 
Test: ✅ 

manager
image
image

Cluster
image
image

**Comment by Tostti** [comment]
# Test
Manager
image
image

Cluster
image
image

**Review by Tostti — APPROVED** [review]
Test ✅ 
CR ✅ 

LGTM

**Review by yenienserrano — APPROVED** [review]
LGTM

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

### Cluster mode disabled

Peek 2024-01-24 19-18

### Cluster mode enabled (with and without filter by node)

Peek 2024-01-24 19-23

**Pull request merged**
