### PR TITLE
Fix ability to filter form FIM details

### LINKED ISSUE #7082: FIM flyout filters not working
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 07 | Chrome, Firefox, Safari, etc |

**Description**
When a user clicks on the filters located in the File Integrity Monitoring / Inventory flyout nothing happens. These filters should trigger the filtering of the value in the main (background) table.

**Screenshots**

Peek 2024-10-08 13-13

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request fixes the ability to filter from the FIM inventory details and add some enhancements.

Changes:
- Fix FIM inventory flyout filters for Files and Registry tabs
- Add ability to filter from Last analysis and Last modified fields from
  Registry details
- Add ability to select the visible columns in the Files and Registry
  tables
- Add to Files table the columns: date (hidden), md5 (hidden), sha1 (hidden), sha256 (hidden)
- Add to Registry table the columns: date (hidden)
- Renamed Last Modified to Last modified in the Files table

### Issues Resolved
#7082

### Evidence
image
image
image

image
image
image
image

### Test
# wdp-pr-7119

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon) | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test
# wdp-pr-7119

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon) | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Chrome - :black_circle:

image
image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Chrome - 🔴

User, User ID, Size, MD5, SHA1 and SHA256 filters are not allowed.

image
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon)</summary>

Chrome - :black_circle:

image
image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon)</summary>

Chrome - :black_circle:

image
image


Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by guidomodarelli** [comment]
### Test
# wdp-pr-7119

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon) | :black_circle: | :black_circle: | :black_circle: |
| With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon) | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
> 🔴 With FIM data in an agent, navigate to File Integrity Monitoring > Files, and choose a file. Adding a field filter from the details flyout will apply the filter to the main table. Next, delete the filter manually and press enter. Subsequently, add another field filter from the details flyout.
> 
>  Peek.2024-10-23.14-42.mp4

I was reviewing this problem and this happens with other tables. I was analyzing it and this could need a deep analysis to fix with a similar solution the affected tables. The problem seems to be visual in the search bar and the queries after applying the filter are ok.

I created an issue to follow it: https://github.com/wazuh/wazuh-dashboard-plugins/issues/7124

**Comment by Desvelao** [comment]
# Changes
- Updated the development branch with latest changes of 4.10.0

**Comment by asteriscos** [comment]
### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Result | 
| --- |  --- | 
| With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :green_circle: | 
| With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search. | :green_circle: | 
| With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon) | :green_circle: | 
| With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon) | :green_circle: | 

**Details**
<details>
<summary>:green_circle: With FIM data in an agent, go to File Integrity Monitoring > Files and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Peek 2024-10-24 13-16


</details>

<details>
<summary> :green_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry (Windows host) and select a file, add a field filter from the details flyout should add the filter to the main table. Try with different fields and ensure the table data is filtered according to the search.</summary>

Peek 2024-10-24 13-17


</details>

<details>
<summary>:green_circle: With FIM data in an agent, go to File Integrity Monitoring > Files, change the visibility of fields columns using the field selector (gear icon)</summary>

Peek 2024-10-24 13-20


</details>

<details>
<summary>:green_circle: With FIM data in an agent, go to File Integrity Monitoring > Registry, change the visibility of fields columns using the field selector (gear icon)</summary>


Peek 2024-10-24 13-19


</details>

**Comment by asteriscos** [comment]
The reported issue about the table not being able to process the same filter twice is out of scope, as it involves refactoring the internal logic of the common tables used in many views. We will evaluate this in a separate issue.

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
