### PR TITLE
Rollback configuration store from saved object to configuration file

### LINKED ISSUE #6570: Rollback the sytem to save the configuration to configuration file
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| X.Y.Z | xyzw | Chrome, Firefox, Safari, etc |

**Description**
In a previous issue https://github.com/wazuh/wazuh-dashboard-plugins/issues/6201, we replaced the system to save the plugin settings into a saved object. We have considered the new system includes some breaking changes, so we delay the change of the configuration system to a future release. So, we will do a rollback to the previous system based on the configuration file, but we keep the enhancements applied in the other issue.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to '...'

**Expected Result**
1. 

**Actual Result**
1. 

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request rollbacks the configuration stored in a saved object to a configuration file.

Changes:
- Rollback:
  - Remove ability to manage the API connections from the Server APIs
    - Remove API endpoints
      - POST /hosts/apis/{id}
      - PUT /hosts/apis/{id}
      - DELETE /hosts/apis/{id}
    - Remove methods in `ManageHosts`
    - Remove form to create or edit the API connection entry
    - Remove buttons to edit or delete the API connection
  - Add information about adding a new API connection
    - Enhance information message with message about configuration cache
  - Remove task to migrate the configuration file to saved object
  - Remove API endpoint to import the configuration file `POST /utils/configuration/import`
  - Remove Encryption service of the backend side
  - Replace the store system of the configuration based on a saved object with the configuration file
  - Change the cache time of configuration from 60 to 10 to match with the previous system
  - Replace the consideration of the administrator user to the previous one based on the `administrator` API 
    connection role
      - Remove API endpoint to get data about the account `GET /utils/account`
- Other enhancements:
  - Redefine the validation of plugins settings:
    - Rename the validation methods:
     > validate -> validateUIForm
     > validateBackend -> validate
    - Reduce the usage of `@osd/config-schema` package (used in the related API endpoints)
  - Remove the transformation of input values to configuration values done by the `useForm` hook and managed externally
  - Minify the references to branding on the default configuration file
  - Change the validation for `enrollment.dns` on App Settings application. Move the `validateServerAddress` to SettingsValidators and replace its usage in the Deploy new agent guide
  - Replace the hard-coded value for the path of the configuration file. It is retrieved from the backend side.
  - Refactor the definition of `getCustomizationSetting` and its usage to get the plugin settings taking into account the hidden values.
  - Remove the default values of some customization settings were displayed on App Settings
  - Fix a problem the `Miscellaneous` tab of `App Settings` application was not accessible from UI
  - Remove deprecated createLogFileIfNotExists method
  - Add tests for ConfigurationStore service of the backend side
 
### Issues Resolved
#6570

### Evidence
image
image
image
image

### Test
# rollback-configuraiton-store

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the Server APIs application does not have the buttons to edit or remove the API application on the Actions column of the table | :black_circle: | :black_circle: | :black_circle: |
| In the Server APIs application, click on the Add API connection and should display information about modifying the configuration file | :black_circle: | :black_circle: | :black_circle: |
| Ensure the customization settings are applied when they are defined and the customization is enabled | :black_circle: | :black_circle: | :black_circle: |
| Go to App Settings application and check it displays the tabs of Configuration and Miscellaneous | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the Server APIs application does not have the buttons to edit or remove the API application on the Actions column of the table</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In the Server APIs application, click on the Add API connection and should display information about modifying the configuration file</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the customization settings are applied when they are defined and the customization is enabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to App Settings application and check it displays the tabs of Configuration and Miscellaneous</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

## Backend

| Test | Result |
| --- |  --- |
| With no configuration file, start Wazuh dashboard, the configuration file should be created with the default configuration | :black_circle: |
| With a defined configuration file, start Wazuh dashboard, and the configuration file should not be replaced by the default content | :black_circle: |
| Go to App Settings, edit a setting, this should be saved into the configuration file | :black_circle: |

**Details**
<details>
<summary>:black_circle: With no configuration file, start Wazuh dashboard, the configuration file should be created with the default configuration</summary>

</details>

<details>
<summary>:black_circle: With a defined configuration file, start Wazuh dashboard, and the configuration file should not be replaced by the default content</summary>

</details>

<details>
<summary>:black_circle: Go to App Settings, edit a setting, this should be saved into the configuration file</summary>

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test
# rollback-configuration-store

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI



| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the Server APIs application does not have the buttons to edit or remove the API application on the Actions column of the table | :black_circle: | :black_circle: | :black_circle: |
| In the Server APIs application, click on the Add API connection and should display information about modifying the configuration file | :black_circle: | :black_circle: | :black_circle: |
| Ensure the customization settings are applied when they are defined and the customization is enabled | :black_circle: | :black_circle: | :black_circle: |
| Go to App Settings application and check it displays the tabs of Configuration and Miscellaneous | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the Server APIs application does not have the buttons to edit or remove the API application on the Actions column of the table</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In the Server APIs application, click on the Add API connection and should display information about modifying the configuration file</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the customization settings are applied when they are defined and the customization is enabled</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to App Settings application and check it displays the tabs of Configuration and Miscellaneous</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

## Backend

| Test | Result |
| --- |  --- |
| With no configuration file, start Wazuh dashboard, the configuration file should be created with the default configuration | :black_circle: |
| With a defined configuration file, start Wazuh dashboard, and the configuration file should be replaced by the default content | :black_circle: |
| Go to App Settings, edit a setting, this should be saved into the configuration file | :black_circle: |

**Details**
<details>
<summary>:black_circle: With no configuration file, start Wazuh dashboard, the configuration file should be created with the default configuration</summary>

</details>

<details>
<summary>:black_circle: With a defined configuration file, start Wazuh dashboard, and the configuration file should be replaced by the default content</summary>

</details>

<details>
<summary>:black_circle: Go to App Settings, edit a setting, this should be saved into the configuration file</summary>

</details>

**Comment by asteriscos** [comment]
## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the Server APIs application does not have the buttons to edit or remove the API application on the Actions column of the table | :green_circle: | :black_circle: | :black_circle: |
| In the Server APIs application, click on the Add API connection and should display information about modifying the configuration file | :green_circle: | :black_circle: | :black_circle: |
| Ensure the customization settings are applied when they are defined and the customization is enabled | :green_circle: | :black_circle: | :black_circle: |
| Go to App Settings application and check it displays the tabs of Configuration and Miscellaneous | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Ensure the Server APIs application does not have the buttons to edit or remove the API application on the Actions column of the table</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: In the Server APIs application, click on the Add API connection and should display information about modifying the configuration file</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Ensure the customization settings are applied when they are defined and the customization is enabled</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Go to App Settings application and check it displays the tabs of Configuration and Miscellaneous</summary>

Chrome - :green_circle:

image


Firefox - :black_circle:

Safari - :black_circle:

</details>

## Backend

| Test | Result |
| --- |  --- |
| With no configuration file, start Wazuh dashboard, the configuration file should be created with the default configuration | :black_circle: |
| With a defined configuration file, start Wazuh dashboard, and the configuration file should be replaced by the default content | :green_circle: |
| Go to App Settings, edit a setting, this should be saved into the configuration file | :green_circle: |

**Details**
<details>
<summary>:black_circle: With no configuration file, start Wazuh dashboard, the configuration file should be created with the default configuration</summary>

</details>

<details>
<summary>:green_circle: With a defined configuration file, start Wazuh dashboard, and the configuration file should be replaced by the default content</summary>

</details>

<details>
<summary>:green_circle: Go to App Settings, edit a setting, this should be saved into the configuration file</summary>

</details>

**Review by asteriscos — DISMISSED** [review]

**Comment by Desvelao** [comment]
# Changes

- Fixed a problem clearing the values for the customization logo settings
- More: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6570#issuecomment-2045046607

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

Peek 2024-04-09 15-07

**Review by JuanGarriuz — APPROVED** [review]

**Pull request merged**
