### PR TITLE
Remove many loading spinners in some views

### LINKED ISSUE #6946: Remove many loading spinners in some views
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | - | Chrome, Firefox, Safari, etc |

**Description**
Currently, the search bar has a loading spinner which makes some views have several loading spinners and also displaces the search bar. We should avoid this by removing the loading of find a way to have a single loading in the page.

**Steps to reproduce**
1. Navigate to MITRE ATT&CK -> Framework
2. See the loading spinners 

Peek 2024-08-26 16-30

### PR DESCRIPTION
**Pull request by guidomodarelli**
### Description
Remove many loading spinners in some views
 
### Issues Resolved
#6946 

### Evidence

Update 2024/09/17

https://github.com/user-attachments/assets/b364f76a-898b-43f4-a178-80559352bfd9

https://github.com/user-attachments/assets/d2da7a44-bb7e-4ebb-84ed-3bfedd809722

https://github.com/user-attachments/assets/3dcf5b45-27b8-4d18-9eed-459c9f16ba40

---

Update 2024/09/16

https://github.com/user-attachments/assets/bd6f9077-166b-4a56-8a7d-158c958b7b33

---

- [x] Create a new loading component
- [x] Apply new loading in `plugins/wazuh/public/components/overview/mitre/framework/mitre.tsx`

<details>

### Before

https://github.com/user-attachments/assets/04c0b337-709b-422d-8a21-bc38b051189c

https://github.com/user-attachments/assets/2f04bb50-917f-4d78-9311-a94be2d20220

### After

https://github.com/user-attachments/assets/a9f77805-6667-468e-8090-91ea907d90ff

https://github.com/user-attachments/assets/9e9b7204-e36b-4bab-8db5-a6605bcc55e0

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/mitre/dashboard/dashboard.tsx`

<details>

### Before

https://github.com/user-attachments/assets/5cd7b5d6-7b04-4b98-b7dd-7230e55413eb

https://github.com/user-attachments/assets/e8cd90d1-7bbd-4cda-a8a1-d3f35766a335

### After

https://github.com/user-attachments/assets/75a6c908-6f3a-4fad-a22f-5dfef15df96a

https://github.com/user-attachments/assets/0f501506-39c0-4848-9188-73758147f366

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/common/wazuh-discover/wz-discover.tsx`

<details>

### Before

https://github.com/user-attachments/assets/a55ae7a3-26c8-4f3e-a35b-50af4080272d

MITRE ATT CK - Events - Before - FIXED

### After

MITRE ATT CK - Events - After
MITRE ATT CK - Events - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/common/wazuh-discover/wz-flyout-discover.tsx`

> In `plugins/wazuh/public/components/agents/fim/inventory/fileDetail.tsx`
<details>

### Before

FIM - Debian Agent - Inventory - FileDetail - Before
FIM - Debian Agent - Inventory - FileDetail - Before - FIXED

### After

FIM - Debian Agent - Inventory - FileDetail - After
FIM - Debian Agent - Inventory - FileDetail - After - FIXED
</details>

> In `plugins/wazuh/public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx`:
<details>

### Before

GDPR - Controls - Before

### After

GDPR - Controls - After
</details>

> In `plugins/wazuh/public/components/overview/mitre/framework/components/techniques/components/flyout-technique/flyout-technique.tsx`:
<details>

### Before

PCI DSS - Controls - Before

### After

PCI DSS - Controls - After
</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/amazon-web-services/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - AWS - Before
MITRE ATT CK - AWS - Before - FIXED

### After

MITRE ATT CK - AWS - After
MITRE ATT CK - AWS - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/docker/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - Docker - Before
MITRE ATT CK - Docker - Before - FIXED

### After

MITRE ATT CK - Docker - After
MITRE ATT CK - Docker - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/fim/dashboard/dashboard.tsx`

<details>

### Before

MITRE ATT CK - FIM - Before
MITRE ATT CK - FIM - Before - FIXED

### After

MITRE ATT CK - FIM - After
MITRE ATT CK - FIM - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/gdpr/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - GDPR - Before
MITRE ATT CK - GDPR - Before - FIXED

### After

MITRE ATT CK - GDPR - After
MITRE ATT CK - GDPR - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/github/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - GitHub - Before
MITRE ATT CK - GitHub - Before - FIXED

### After

MITRE ATT CK - GitHub - After
MITRE ATT CK - GitHub - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/google-cloud/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - Google Cloud - Before
MITRE ATT CK - Google Cloud - Before - FIXED

### After

MITRE ATT CK - Google Cloud - After
MITRE ATT CK - Google Cloud - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/hipaa/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - HIPAA - Before
MITRE ATT CK - HIPAA - Before - FIXED

### After

MITRE ATT CK - HIPAA - After
MITRE ATT CK - HIPAA - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/malware-detection/dashboard/dashboard.tsx`

<details>

### Before

MITRE ATT CK - Malware Detection - Before
MITRE ATT CK - Malware Detection - Before - FIXED

### After

MITRE ATT CK - Malware Detection - After
MITRE ATT CK - Malware Detection - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/nist/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - NIST - Before
MITRE ATT CK - NIST - Before - FIXED

### After

MITRE ATT CK - NIST - After
MITRE ATT CK - NIST - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/office/dashboard/dashboard.tsx`

<details>

### Before

MITRE ATT CK - Office - Before
MITRE ATT CK - Office - Before - FIXED

### After

MITRE ATT CK - Office - After
MITRE ATT CK - Office - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/pci/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - PCI - Before
MITRE ATT CK - PCI - Before - FIXED

### After

MITRE ATT CK - PCI - After
MITRE ATT CK - PCI - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/threat-hunting/dashboard/dashboard.tsx`

<details>

### Before

MITRE ATT CK - Threat Hunting - Before
MITRE ATT CK - Threat Hunting - Before - FIXED

### After

MITRE ATT CK - Threat Hunting - After
MITRE ATT CK - Threat Hunting - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/tsc/dashboards/dashboard.tsx`

<details>

### Before

MITRE ATT CK - TSC - Before
MITRE ATT CK - TSC - Before - FIXED

### After

MITRE ATT CK - TSC - After
MITRE ATT CK - TSC - After - FIXED

</details>

- [x] Apply new loading in `plugins/wazuh/public/components/overview/virustotal/dashboard/dashboard.tsx`

<details>

### Before

MITRE ATT CK - VirusTotal - Before
MITRE ATT CK - VirusTotal - Before - FIXED

### After

MITRE ATT CK - VirusTotal - After
MITRE ATT CK - VirusTotal - After - FIXED

</details>

### Tests
1. Navigate to "Threat intelligence" » "MITRE ATT&CK"
MITRE ATT CK - How to test

2. See the Loading Search Progress

> How to test File Integrity Monitoring
1. Click On "Menu"
2. Expand "Endpoint Security"
3. Click On "File Integrity Monitoring"
4. Select "Inventory" tab
5. Click On "Select agent"
6. Select "Debian agent" (ID: 001)
7. Select "/etc/resolv.conf" file
8. See the Loading Search Progress

https://github.com/user-attachments/assets/b7bb5318-46d0-4560-85f2-f544d00df3e6

> How to test GDPR
1. Click On "Menu"
2. Expand "Security Operations"
3. Click On "GDPR"
4. Select "Control" tab
5. Click On any requirement
6. See the Loading Search Progress

https://github.com/user-attachments/assets/70f30793-17d4-401d-a0dd-7f2610488b7b

> How to test PCI DSS
1. Click On "Menu"
2. Expand "Security Operations"
3. Click On "PCI DSS"
4. Select "Control" tab
5. Click On any requirement
6. See the Loading Search Progress

https://github.com/user-attachments/assets/39109fdb-b2df-456a-948c-e547a3e0fc62

> How to test HIPAA
1. Click On "Menu"
2. Expand "Security Operations"
3. Click On "HIPAA"
4. Select "Control" tab
5. Click On any requirement
6. See the Loading Search Progress

> How to test NIST 800-53
1. Click On "Menu"
2. Expand "Security Operations"
3. Click On "NIST 800-53"
4. Select "Control" tab
5. Click On any requirement
6. See the Loading Search Progress

> How to test TSC
1. Click On "Menu"
2. Expand "Security Operations"
3. Click On "TSC"
4. Select "Control" tab
5. Click On any requirement
6. See the Loading Search Progress

> How to test MITRE ATT&CK
1. Click On "Menu"
2. Expand "Threat intelligence"
3. Click On "MITRE ATT&CK"
4. Select "Framework" tab
5. Click On any requirement
6. See the Loading Search Progress

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by guidomodarelli** [comment]
### Before

https://github.com/user-attachments/assets/eac83f20-4916-4c74-90ca-5925a2a86e15

### After

https://github.com/user-attachments/assets/c5dc4bed-cca4-430b-815b-a3d166ae03a4

**Review by Machi3mfl — APPROVED** [review]
CR: ✅ 
Test: ✅ 


https://github.com/user-attachments/assets/5bdfffd8-1bf8-4fd2-8906-e63da7936baf

**Review by asteriscos — COMMENTED** [review]
Test :yellow_circle: 

The search bar progress works as expected, but the vulnerabilities dashboard and inventory don't implement it. This makes it inconsistent with the rest of the dashboards.

**Review by asteriscos — APPROVED** [review]
CR: :green_circle: 
Test: :green_circle: 

### Threat hunting

<details>

Peek 2024-09-17 17-32


</details>


### Vulnerabilities

<details>

Peek 2024-09-17 17-21


</details>


### GDPR

<details>

Peek 2024-09-17 17-25

Peek 2024-09-17 17-33


</details>

### MITRE ATT&CK

<details>

Peek 2024-09-17 17-26


</details>

### FIM

<details>

Peek 2024-09-17 17-28


</details>

### GitHub

<details>

Peek 2024-09-17 17-29


</details>

### Cluster

Peek 2024-09-17 17-30

**Review by chantal-kelm — COMMENTED** [review]
FIM

When you go from the Dashboard tab to the Inventory in fim you do not see loading

https://github.com/user-attachments/assets/93ba61be-0ccf-414e-897a-fca0fcfbb194

**Comment by asteriscos** [comment]
> FIM
> 
> When you go from the Dashboard tab to the Inventory in FIM you do not see loading
> 
>  Grabacion.de.pantalla.2024-09-17.a.la.s.2.40.53.p.m.mov

Fim -> Inventory tab doesn't have the global search bar, therefore it doesn't render the progress loading state.

**Review by chantal-kelm — APPROVED** [review]
CR: :green_circle: 
Test: :green_circle: 

### Threat hunting

<details>

https://github.com/user-attachments/assets/9bbe03b1-90db-49d0-ba69-3afc15d1978d

</details>


### Vulnerabilities

<details>


https://github.com/user-attachments/assets/72cf30f2-d865-4cf5-a0f8-ff72a9856a8f


</details>


### GDPR

<details>


https://github.com/user-attachments/assets/a3b04a70-5010-4b4a-991f-b0ff1b330bb3


https://github.com/user-attachments/assets/608552b3-98b4-4cb4-8579-074260014e92




</details>

### MITRE ATT&CK

<details>


https://github.com/user-attachments/assets/b0f1bc26-7dbc-40fc-86fb-f36d0c4b4368




</details>

### FIM

<details>


https://github.com/user-attachments/assets/f7e3c4eb-5ce8-4b71-9b5f-d72bb25654ac


https://github.com/user-attachments/assets/2269bf71-0c5e-497a-a33b-73d1a41e1207




</details>

### GitHub

<details>


https://github.com/user-attachments/assets/009360cd-5fe5-47cb-9a05-0075cc209429




</details>

### Cluster

<details>

https://github.com/user-attachments/assets/db3224a0-c437-4990-99f6-500f99308798


</details>

https://github.com/user-attachments/assets/b513a69e-6dfe-4d8c-b8e5-5c6e346c30e0

**Pull request merged**
