### PR TITLE
Add field links in discover document details

### LINKED ISSUE #6837: Missing module links in Documents Details Flyout in Discover
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0| beta1 | Chrome, Firefox, Safari, etc |

**Description**

The Discover contains some fields that should have link to different places. Currently, the details flyout doesn't have those links, and the fields are not clickable.

## Current

Screenshot 2024-07-18 at 08 58 07

## Expected

Screenshot 2024-07-18 at 08 42 34

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description

Add field links in discover document details
 
Closes #6837 

### Evidence

Screenshot 2024-07-18 at 09 54 15

## Tests

- Check the `Threat Hunting` data grid. The flyout details must have the same links as the table

https://github.com/user-attachments/assets/2a345437-5bcf-4851-8303-e8a322fe2dbb

- Check the modules `Events` tab data grid. The flyout details must have the same links as the table

https://github.com/user-attachments/assets/fc069964-d2fb-4a91-97b5-b454fb45447d

https://github.com/user-attachments/assets/1f0794e1-621a-4231-adbb-9645abc082bb

- Check the module Vulnerability Detection `Inventory` tab data grid. The flyout details must have the same links as the table

https://github.com/user-attachments/assets/1441cfaa-086f-4f35-9212-746b2ce13d87

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by yenienserrano** [comment]
The agent.name link does not work

image

**Comment by Machi3mfl** [comment]
> The agent.name link does not work
> 
> image

Solved in https://github.com/wazuh/wazuh-dashboard-plugins/pull/6843/commits/ddb890564fa6d37e986c24d72b11fcdc8a2752b3


https://github.com/user-attachments/assets/565e96aa-5495-445c-a4fb-709b263ccbae

**Comment by yenienserrano** [comment]
Test: 🟢 

image

image

image

**Review by yenienserrano — DISMISSED** [review]
CR: 🟢

**Review by chantal-kelm — DISMISSED** [review]
CR: ✅ 
Test: ✅ 

🟢 Check the Threat Hunting data grid. The flyout details must have the same links as the table
<details>

https://github.com/user-attachments/assets/b0328c19-e19f-4a03-9f0a-138373b02c1b

</details>

🟢 Check the modules Events tab data grid. The flyout details must have the same links as the table
<details>

https://github.com/user-attachments/assets/9c4077cb-9998-457b-9754-fec02ee0fb9e

https://github.com/user-attachments/assets/f65493e9-ec15-4ceb-954b-c7416b51fb16

</details>

🟢 Check the module Vulnerability Detection Inventory tab data grid. The flyout details must have the same links as the table

<details>

https://github.com/user-attachments/assets/f9cc5335-336c-466d-adab-c650b63f4b5f

</details>

**Review by yenienserrano — APPROVED** [review]

**Review by chantal-kelm — APPROVED** [review]

**Review by chantal-kelm — APPROVED** [review]

**Pull request merged**
